version: "3.8"

x-default-env:  &default-env
  environment:
    DATABASE_NAME: "${DATABASE_NAME:-africultures}"  # database name
    DATABASE_USERNAME: "${DATABASE_USERNAME:-postgres}" # default username
    DATABASE_PASSWORD: "${DATABASE_PASSWORD:-postgres}" # default password

    DATABASE_HOST: "${DATABASE_HOST:-host.docker.internal}" # 'host.docker.internal'
    RABBIT_HOST: rabbit
    RABBIT_PASSWORD: carrot
    DEBUG: 'False'

x-default-volumes:  &default-volumes
  volumes:
    - './docker-entrypoint.sh:/docker-entrypoint'
    - "./mproj:/src"
    - "${AFRICULTURE_AUX_FILES:-./local_files/aux_files}:/aux_files"
    - "${AFRICULTURES_LOCAL_FILES_ROOT:-./local_files/local_files_root}:/local_files_root"

x-default-build: &x-default-build
    image: "vesnikos/eo_engine:latest"
    build:
      context: .
      dockerfile: "docker/worker/Dockerfile"

services:

  engine: &engine
    <<: *x-default-build
    <<: *default-volumes
    <<: *default-env

  rabbit:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"
      - "8080:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 5s
      retries: 3
    volumes:
      - "./docker/rabbit/etc/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro"

  worker:
    <<: *engine
    entrypoint: '/docker-entrypoint'
    command: [ 'worker' ]

  beat:
    <<: *engine
    entrypoint: '/docker-entrypoint'
    command: [ 'beat' ]

  web:
    <<: *default-env
    <<: *default-volumes
    <<: *x-default-build
    command:
      - "python"
      - "/src/manage.py"
      - "runserver"
      - "0.0.0.0:8000"
    depends_on:
      - rabbit
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: "${DATABASE_NAME:-africultures}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD:-postgres}"
      POSTGRES_USER: "${DATABASE_USERNAME:-postgres}"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - "${LOCAL_DB_ROOT:-./local_files/pg_data}:/var/lib/postgresql/data"
