version: "3"

x-default-env: &default-env
  environment:
    DATABASE_PASSWORD: postgres
    DATABASE_NAME: postgres
    DATABASE_USERNAME: postgres
    DATABASE_HOST: "host.docker.internal"
    RABBIT_HOST: rabbit
    RABBIT_PASSWORD: carrot
    DEBUG: 'False'

x-default-volumes: &default-volumes
  volumes:
    - './docker-entrypoint.sh:/docker-entrypoint'
    - "./mproj:/src"
    - "./local_files/local_files_root:/local_files_root"  # local file repo


services:

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./local_files/pg_data:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:3.8-management
    ports:
      - 5672:5672
      - 8080:15672
    volumes:
      - "./docker/rabbit/etc/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro"

  worker:
    <<: *default-env
    <<: *default-volumes
    image: vesnikos/eo_engine:0.2.0
    entrypoint: '/docker-entrypoint'
    command: [ 'worker' ]

  beat:
    <<: *default-env
    <<: *default-volumes
    image: vesnikos/eo_engine:0.2.0
    entrypoint: '/docker-entrypoint'
    command: [ 'beat' ]

  web:
    <<: *default-env
    <<: *default-volumes
    image: vesnikos/eo_engine:0.2.0
    entrypoint: '/docker-entrypoint'
    command: [ 'web' ]
    ports:
      - 8000:8000
