# Generated by Django 3.2 on 2021-05-14 11:55

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EOSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_seen', models.DateTimeField(auto_created=True)),
                ('status', models.CharField(choices=[('availableRemotely', 'available Remotely'), ('availableLocally', 'available Locally'), ('ignore', 'ignore')], default='availableRemotely', max_length=255)),
                ('product', models.CharField(choices=[('ndvi-300m-v1', 'ndvi 300m v1'), ('ndvi-300m-v2', 'ndvi 300m v2'), ('ndvi-1km-v3', 'ndvi 1km v3'), ('ndvi-1km-v2', 'ndvi 1km v2'), ('ndvi-1km-v1', 'ndvi 1km v1'), ('lai-300m-v1', 'lai 300m v1'), ('lai-1km-v1', 'lai 1km v1'), ('lai-1km-v2', 'lai 1km v2'), ('vc1-v1', 'vc1 v1'), ('wb-africa-v1', 'wb africa V1')], max_length=255)),
                ('file', models.FileField(editable=False, max_length=1000, upload_to='')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('extension', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=200)),
                ('datetime_uploaded', models.DateTimeField()),
                ('url', models.URLField()),
                ('credentials', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eo_engine.credentials')),
            ],
        ),
        migrations.CreateModel(
            name='EOProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_creation', models.DateTimeField(auto_created=True)),
                ('filename', models.TextField(unique=True)),
                ('product', models.CharField(choices=[('agro-ndvi-1km-v3', 'ndvi 1km v3 (lab-made)')], max_length=255)),
                ('location', models.TextField()),
                ('process', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('inputs', models.ManyToManyField(to='eo_engine.EOSource')),
            ],
        ),
    ]
