# Generated by Django 3.2 on 2021-04-20 17:48

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Credentials = apps.get_model("eo_engine", "Credentials")

    Credentials.objects.bulk_create([
        Credentials(domain="vito-eodata.be", username="vesnikos", password="J7Ri5x78WjWHhEZ"),
        Credentials(domain="land.copernicus.vgt.vito.be", username="vesnikos", password="vYxDWrstV265PDF"),

    ])


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    Credentials = apps.get_model("eo_engine", "Credentials")

    db_alias = schema_editor.connection.alias
    Credentials.objects.filter(domain="vito-eodata.be").delete()
    Credentials.objects.filter(domain="land.copernicus.vgt.vito.be").delete()


class Migration(migrations.Migration):
    dependencies = [
        ('eo_engine', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
