# Generated by Django 3.2 on 2021-05-14 16:55

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0002_creds'),
    ]

    operations = [
        migrations.CreateModel(
            name='UBDCGroupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_task_id', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('root_id', models.UUIDField(db_index=True, editable=False, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('datetime_started', models.DateTimeField(null=True)),
                ('datetime_finished', models.DateTimeField(null=True)),
                ('op_name', models.TextField(blank=True, null=True)),
                ('op_args', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('op_kwargs', models.JSONField(default=dict)),
                ('op_initiator', models.TextField(default='', max_length=255)),
            ],
            options={
                'ordering': ['timestamp'],
                'unique_together': {('group_task_id', 'root_id')},
            },
        ),
        migrations.CreateModel(
            name='UBDCTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('task_name', models.TextField()),
                ('task_args', models.TextField(default='[]')),
                ('parent_id', models.UUIDField(db_index=True, editable=False, null=True)),
                ('status', models.TextField(choices=[('SUBMITTED', 'Submitted'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('REVOKED', 'Revoked'), ('RETRY', 'Retry'), ('UNKNOWN', 'Unknown')], db_index=True, default='SUBMITTED')),
                ('datetime_submitted', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('datetime_started', models.DateTimeField(blank=True, null=True)),
                ('datetime_finished', models.DateTimeField(blank=True, null=True)),
                ('time_to_complete', models.TextField(blank=True, default='')),
                ('retries', models.IntegerField(default=0)),
                ('task_kwargs', models.JSONField(default=dict)),
                ('root_id', models.UUIDField(db_index=True, editable=False, null=True)),
                ('group_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ubdc_tasks', related_query_name='ubdc_task', to='eo_engine.ubdcgrouptask', to_field='group_task_id')),
            ],
            options={
                'ordering': ['datetime_submitted'],
            },
        ),
        migrations.AddIndex(
            model_name='ubdctask',
            index=django.contrib.postgres.indexes.GinIndex(fields=['task_kwargs'], name='eo_engine_u_task_kw_01ac62_gin'),
        ),
    ]
