# Generated by Django 3.2 on 2021-05-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0004_auto_20210517_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='eoproduct',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available for production'), ('PROCESSING', 'Processing...'), ('READY', 'Ready')], default='AVAILABLE', max_length=255),
        ),
        migrations.AddField(
            model_name='eosource',
            name='product_group',
            field=models.CharField(choices=[('ndvi', 'NDVI'), ('lai', 'LAI'), ('fcover', 'FCOVER'), ('fapar', 'FAPAR'), ('dmp', 'DMP'), ('gdmp', 'GDMP')], default='NDVI', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eoproduct',
            name='location',
            field=models.FileField(null=True, upload_to='agro_products'),
        ),
    ]
