# Generated by Django 3.2 on 2021-05-17 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0005_auto_20210517_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='eoproduct',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eoproduct',
            name='datetime_creation',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='eosource',
            name='status',
            field=models.CharField(choices=[('availableRemotely', 'Availableremotely'), ('availableLocally', 'Availablelocally'), ('Ignore', 'Ignore')], default='availableRemotely', max_length=255),
        ),
    ]
