# Generated by Django 3.2 on 2021-05-18 15:36

from django.db import migrations, models
import eo_engine.models.eo_source


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0006_auto_20210517_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eosource',
            name='file',
            field=models.FileField(editable=False, max_length=2048, null=True, upload_to=eo_engine.models.eo_source._file_storage_path),
        ),
    ]
