# Generated by Django 3.2 on 2021-05-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0007_alter_eosource_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eoproduct',
            old_name='location',
            new_name='file',
        ),
    ]
