# Generated by Django 3.2.3 on 2021-05-31 17:58

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import eo_engine.models.eo_product


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0008_rename_location_eoproduct_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeopTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('task_name', models.TextField()),
                ('task_args', models.TextField(default='[]')),
                ('parent_id', models.UUIDField(db_index=True, editable=False, null=True)),
                ('status', models.TextField(choices=[('SUBMITTED', 'Submitted'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('REVOKED', 'Revoked'), ('RETRY', 'Retry'), ('UNKNOWN', 'Unknown')], db_index=True, default='SUBMITTED')),
                ('datetime_submitted', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('datetime_started', models.DateTimeField(blank=True, null=True)),
                ('datetime_finished', models.DateTimeField(blank=True, null=True)),
                ('time_to_complete', models.TextField(blank=True, default='')),
                ('retries', models.IntegerField(default=0)),
                ('task_kwargs', models.JSONField(default=dict)),
                ('root_id', models.UUIDField(db_index=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['datetime_submitted'],
            },
        ),
        migrations.AlterField(
            model_name='eoproduct',
            name='file',
            field=models.FileField(max_length=2048, null=True, upload_to=eo_engine.models.eo_product._upload_to),
        ),
        migrations.AlterField(
            model_name='eosource',
            name='status',
            field=models.CharField(choices=[('availableRemotely', 'Availableremotely'), ('availableLocally', 'Availablelocally'), ('BeingDownloaded', 'Beingdownloaded'), ('Ignore', 'Ignore')], default='availableRemotely', max_length=255),
        ),
        migrations.RenameModel(
            old_name='UBDCGroupTask',
            new_name='GeopGroupTask',
        ),
        migrations.DeleteModel(
            name='UBDCTask',
        ),
        migrations.AddField(
            model_name='geoptask',
            name='group_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='geop_tasks', related_query_name='geop_task', to='eo_engine.geopgrouptask', to_field='group_task_id'),
        ),
        migrations.AddIndex(
            model_name='geoptask',
            index=django.contrib.postgres.indexes.GinIndex(fields=['task_kwargs'], name='eo_engine_g_task_kw_f78125_gin'),
        ),
    ]
