# Generated by Django 3.2.4 on 2021-06-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0009_auto_20210531_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eosource',
            name='datetime_seen',
            field=models.DateTimeField(auto_created=True, help_text='datetime of when it was seen'),
        ),
        migrations.AlterField(
            model_name='eosource',
            name='datetime_uploaded',
            field=models.DateTimeField(help_text='datetime of when it was uploaded', null=True),
        ),
        migrations.AlterField(
            model_name='eosource',
            name='product',
            field=models.CharField(choices=[('ndvi-300m-v1', 'ndvi 300m v1'), ('ndvi-300m-v2', 'ndvi 300m v2'), ('ndvi-1km-v3', 'ndvi 1km v3'), ('ndvi-1km-v2', 'ndvi 1km v2'), ('ndvi-1km-v1', 'ndvi 1km v1'), ('lai-300m-v1', 'lai 300m v1'), ('lai-1km-v1', 'lai 1km v1'), ('lai-1km-v2', 'lai 1km v2'), ('vc1-v1', 'vc1 v1'), ('wb-africa-v1', 'wb africa V1'), ('sirs-nrt-300', 'SIRS WB NRT 300m'), ('sirs-nrt-100', 'SIRS WB NRT 100m')], max_length=255),
        ),
        migrations.AlterField(
            model_name='eosource',
            name='product_group',
            field=models.CharField(choices=[('ndvi', 'NDVI'), ('lai', 'LAI'), ('fcover', 'FCOVER'), ('fapar', 'FAPAR'), ('dmp', 'DMP'), ('gdmp', 'GDMP'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='eosource',
            name='url',
            field=models.URLField(help_text='Resource URL'),
        ),
    ]
