# Generated by Django 3.2.4 on 2021-06-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0011_creds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eosource',
            name='datetime_uploaded',
        ),
        migrations.RemoveField(
            model_name='eosource',
            name='product_group',
        ),
        migrations.AddField(
            model_name='eosource',
            name='datetime_reference',
            field=models.DateTimeField(help_text='product reference datetime ', null=True),
        ),
        migrations.AlterField(
            model_name='eosource',
            name='product',
            field=models.CharField(choices=[('c_gsl_NDVI300-V2-GLOB', 'Copernicus Global Land Service NDVI 300m v2'), ('c_gsl_NDVI1km-V3-GLOB', 'Copernicus Global Land Service NDVI 1km v3'), ('a_agro_NDVI300-V3-AFR', 'AuthAgro Service NDVI 1km v3'), ('c_gsl_LAI300-V1-GLOB', 'Copernicus Global Land Service LAI 300m v1')], max_length=255),
        ),
    ]
