# Generated by Django 3.2.4 on 2021-06-27 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0012_auto_20210627_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='eosource',
            name='filesize_reported',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eosource',
            name='product',
            field=models.CharField(choices=[('c_gsl_NDVI300-V2-GLOB', 'Copernicus Global Land Service NDVI 300m v2'), ('c_gsl_NDVI1km-V3-GLOB', 'Copernicus Global Land Service NDVI 1km v3'), ('a_agro_NDVI300-V3-AFR', 'AuthAgro Service NDVI 1km v3'), ('c_gsl_LAI300-V1-GLOB', 'Copernicus Global Land Service LAI 300m v1'), ('c_gls_WB100-V1-GLOB', 'Copernicus Global Land Service Water Bodies Collection 100m Version 1')], max_length=255),
        ),
    ]
