# Generated by Django 3.2.4 on 2021-06-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0013_auto_20210627_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='eoproduct',
            name='output_folder',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eoproduct',
            name='product',
            field=models.CharField(choices=[('agro-ndvi-1km-v3', 'A Agro Ndvi 1Km V3'), ('WB-100m-TUN', 'A Agro Wb 100M Tun'), ('WB-100m-RWA', 'A Agro Wb 100M Rwa'), ('WB-100m-ETH', 'A Agro Wb 100M Eth'), ('WB-100m-MOZ', 'A Agro Wb 100M Moz'), ('WB-100m-ZAF', 'A Agro Wb 100M Zaf'), ('WB-100m-GHA', 'A Geop Wb 100M Gha'), ('WB-100m-NER', 'A Geop Wb 100M Ner')], max_length=255),
        ),
    ]
