# Generated by Django 3.2.4 on 2021-06-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0014_auto_20210627_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eoproduct',
            name='process',
        ),
        migrations.AddField(
            model_name='eoproduct',
            name='task_kwargs',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eoproduct',
            name='task_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eoproduct',
            name='status',
            field=models.CharField(choices=[('Available', 'Available to be made'), ('Failed', 'Generation was attempted but failed'), ('InProcess', 'InProcess...'), ('Ready', 'Product is Ready.')], default='Available', max_length=255),
        ),
    ]
