# Generated by Django 3.2.4 on 2021-06-27 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0015_auto_20210627_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eosource',
            name='filesize_reported',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
