# Generated by Django 3.2.4 on 2021-06-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0016_alter_eosource_filesize_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoproduct',
            name='status',
            field=models.CharField(choices=[('Available', 'Available to be made'), ('Scheduled', 'Scheduled For Making'), ('Failed', 'Generation was attempted but failed'), ('InProcess', 'InProcess...'), ('Ready', 'Product is Ready.')], default='Available', max_length=255),
        ),
        migrations.AlterField(
            model_name='eosource',
            name='status',
            field=models.CharField(choices=[('availableRemotely', 'NO_LABEL'), ('ScheduledForDownload', 'Scheduled For Download'), ('availableLocally', 'NO_LABEL'), ('BeingDownloaded', 'NO_LABEL'), ('Ignore', 'NO_LABEL')], default='availableRemotely', max_length=255),
        ),
    ]
