# Generated by Django 3.2.4 on 2021-06-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0017_auto_20210627_2015'),
    ]

    operations = [
    ]
