# Generated by Django 3.2.5 on 2021-07-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0020_auto_20210627_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('rules', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name='eoproduct',
            name='status',
            field=models.CharField(choices=[('Available', 'Available for generation.'), ('Scheduled', 'Scheduled For generation.'), ('Failed', 'Generation was attempted but failed'), ('Generating', 'Product is being generated.'), ('Ready', 'Product is Ready.')], default='Available', max_length=255),
        ),
    ]
