# Generated by Django 3.2.5 on 2021-07-09 11:20

from django.db import migrations

init_rules_download = {
    "rules":
        [
            {
                "type": "c_gsl_ndvi300-v2-glob",
                "start_date": "1/07/2020"
            },
            {
                "type": "c_gsl_lai300-v1-glob",
                "start_date": "1/07/2020"
            },
            {
                "type": "c_gls_wb100-v1-glob",
                "start_date": "01/11/2020"
            }
        ]
}


def forwards_func(apps, schema_editor):
    # add initial entry
    FR = apps.get_model("eo_engine", "FunctionalRules")

    FR.objects.bulk_create([
        FR(domain="download_rules", rules=init_rules_download),
        FR(domain='ignore_products', rules={"ignore_products": []})

    ])


def reverse_func(apps, schema_editor):
    # delete all entries
    FR = apps.get_model("eo_engine", "FunctionalRules")
    FR.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('eo_engine', '0021_auto_20210709_1053'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
