# Generated by Django 3.2.5 on 2021-07-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0022_rules_fixture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eoproduct',
            old_name='product',
            new_name='product_group'
        ),
        migrations.AlterField(
            model_name='eoproduct',
            name='status',
            field=models.CharField(choices=[('Available', 'Available for generation.'), ('Scheduled', 'Scheduled For generation.'), ('Failed', 'Generation was attempted but failed'), ('Generating', 'Product is being generated.'), ('Ignore', 'Ignore.'), ('Ready', 'Product is Ready.')], default='Available', max_length=255),
        ),
    ]
