# Generated by Django 3.2.5 on 2021-07-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0023_auto_20210711_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoproduct',
            name='product_group',
            field=models.CharField(choices=[('agro_ndvi-1km-v3-afr', 'A Agro Ndvi 1Km V3'), ('agro_ndvi-300m-v3-afr', 'A Agro Ndvi 300M V2'), ('agro_wb-100m-tun', 'A Agro Wb 100M Tun'), ('agro_wb-100m-rwa', 'A Agro Wb 100M Rwa'), ('agro_wb-100m-eth', 'A Agro Wb 100M Eth'), ('agro_wb-100m-moz', 'A Agro Wb 100M Moz'), ('agro_wb-100m-zaf', 'A Agro Wb 100M Zaf'), ('agro_wb-100m-gha', 'A Geop Wb 100M Gha'), ('agro_wb-100m-ner', 'A Geop Wb 100M Ner')], max_length=255),
        ),
    ]
