# Generated by Django 3.2.5 on 2021-07-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0024_alter_eoproduct_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eosource',
            name='product',
            field=models.CharField(choices=[('c_gsl_ndvi300-V2-glob', 'Copernicus Global Land Service NDVI 300m v2'), ('c_gsl_NDVI1km-V3-GLOB', 'Copernicus Global Land Service NDVI 1km v3'), ('a_agro_NDVI300-V3-AFR', 'AuthAgro Service NDVI 1km v3'), ('c_gsl_LAI300-V1-GLOB', 'Copernicus Global Land Service LAI 300m v1'), ('c_gls_WB100-V1-GLOB', 'Copernicus Global Land Service Water Bodies Collection 100m Version 1')], max_length=255),
        ),
    ]
