# Generated by Django 3.2.5 on 2021-07-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0025_alter_eosource_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoproduct',
            name='product_group',
            field=models.CharField(choices=[('agro_ndvi-1km-v3-afr', 'A Agro Ndvi 1Km V3'), ('agro_ndvi-300m-v3-afr', 'A Agro Ndvi 300M V2'), ('agro_lai-300m-v1-afr', 'A Agro Lai 300M V1 Afr'), ('agro_lai_1km-v2-afr', 'A Agro Lai 1Km V2 Afr'), ('agro_wb-100m-tun', 'A Agro Wb 100M Tun'), ('agro_wb-100m-rwa', 'A Agro Wb 100M Rwa'), ('agro_wb-100m-eth', 'A Agro Wb 100M Eth'), ('agro_wb-100m-moz', 'A Agro Wb 100M Moz'), ('agro_wb-100m-zaf', 'A Agro Wb 100M Zaf'), ('agro_wb-100m-gha', 'A Geop Wb 100M Gha'), ('agro_wb-100m-ner', 'A Geop Wb 100M Ner')], max_length=255),
        ),
        migrations.AlterField(
            model_name='eosource',
            name='product',
            field=models.CharField(choices=[('c_gsl_ndvi300-V2-glob', 'Copernicus Global Land Service NDVI 300m v2'), ('c_gsl_ndvi1km-v3-glob', 'Copernicus Global Land Service NDVI 1km v3'), ('a_agro_ndvi300-v3-afr', 'AuthAgro Service NDVI 1km v3'), ('c_gsl_lai300-v1-glob', 'Copernicus Global Land Service LAI 300m v1'), ('c_gls_WB100-V1-GLOB', 'Copernicus Global Land Service Water Bodies Collection 100m Version 1')], max_length=255),
        ),
    ]
