# Generated by Django 3.2.5 on 2021-07-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0026_auto_20210711_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eosource',
            name='product',
            field=models.CharField(choices=[('c_gsl_ndvi300-v2-glob', 'Copernicus Global Land Service NDVI 300m v2'), ('c_gsl_ndvi1km-v3-glob', 'Copernicus Global Land Service NDVI 1km v3'), ('a_agro_ndvi300-v3-afr', 'AuthAgro Service NDVI 1km v3'), ('c_gsl_lai300-v1-glob', 'Copernicus Global Land Service LAI 300m v1'), ('c_gls_wb100-v1-glob', 'Copernicus Global Land Service Water Bodies Collection 100m Version 1')], max_length=255),
        ),
    ]
