# Generated by Django 3.2.5 on 2021-07-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0027_alter_eosource_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eoproduct',
            options={'ordering': ['product_group', 'filename']},
        ),
        migrations.AlterModelOptions(
            name='eosource',
            options={'ordering': ['product', '-datetime_reference']},
        ),
        migrations.RenameField(
            model_name='eoproduct',
            old_name='inputs',
            new_name='eo_sources_inputs',
        ),
        migrations.AddField(
            model_name='eoproduct',
            name='eo_products_inputs',
            field=models.ManyToManyField(related_name='_eo_engine_eoproduct_eo_products_inputs_+', to='eo_engine.EOProduct'),
        ),
        migrations.AlterField(
            model_name='eoproduct',
            name='product_group',
            field=models.CharField(choices=[('agro_ndvi-1km-v3-afr', 'AUTH/AGRO/NDVI 1km, V3 Africa'), ('agro_ndvi-300m-v3-afr', 'AUTH/AGRO/NDVI NDVI 300, V3 Africa'), ('agro_lai-300m-v1-afr', 'AUTH/AGRO/LAI 300m, V1 Africa'), ('agro_lai_1km-v2-afr', 'AUTH/AGRO/LAI 1km, V2 Africa'), ('agro_wb-100m-tun', 'A Agro Wb 100M Tun'), ('agro_wb-100m-rwa', 'A Agro Wb 100M Rwa'), ('agro_wb-100m-eth', 'A Agro Wb 100M Eth'), ('agro_wb-100m-moz', 'A Agro Wb 100M Moz'), ('agro_wb-100m-zaf', 'A Agro Wb 100M Zaf'), ('agro_wb-100m-gha', 'A Geop Wb 100M Gha'), ('agro_wb-100m-ner', 'A Geop Wb 100M Ner')], max_length=255),
        ),
        migrations.AlterField(
            model_name='eoproduct',
            name='status',
            field=models.CharField(choices=[('Available', 'AVAILABLE for generation.'), ('Scheduled', 'SCHEDULED For generation.'), ('Failed', 'Generation was attempted but FAILED'), ('Generating', 'GENERATING...'), ('Ignore', 'Ignore.'), ('Ready', 'Product is READY.')], default='Available', max_length=255),
        ),
        migrations.AlterField(
            model_name='eosource',
            name='status',
            field=models.CharField(choices=[('availableRemotely', 'Available on the Remote Server'), ('ScheduledForDownload', 'Scheduled For Download'), ('availableLocally', 'File available locally'), ('BeingDownloaded', 'File is Being downloaded'), ('Ignore', 'IgnoreFile')], default='availableRemotely', max_length=255),
        ),
    ]
