# Generated by Django 3.2.5 on 2021-08-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0028_auto_20210722_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoproduct',
            name='eo_products_inputs',
            field=models.ManyToManyField(to='eo_engine.EOProduct'),
        ),
        migrations.AlterField(
            model_name='eoproduct',
            name='product_group',
            field=models.CharField(choices=[('agro_ndvi-1km-v3-afr', 'AUTH/AGRO/NDVI 1km, V3 Africa'), ('agro_ndvi-300m-v3-afr', 'AUTH/AGRO/NDVI 300m, V3 Africa'), ('agro_vci-10km-v2-afr', 'AUTH/AGRO/VCI 1km, V2 Africa'), ('agro_lai-300m-v1-afr', 'AUTH/AGRO/LAI 300m, V1 Africa'), ('agro_lai_1km-v2-afr', 'AUTH/AGRO/LAI 1km, V2 Africa'), ('agro_wb-100m-tun', 'A Agro Wb 100M Tun'), ('agro_wb-100m-rwa', 'A Agro Wb 100M Rwa'), ('agro_wb-100m-eth', 'A Agro Wb 100M Eth'), ('agro_wb-100m-moz', 'A Agro Wb 100M Moz'), ('agro_wb-100m-zaf', 'A Agro Wb 100M Zaf'), ('agro_wb-100m-gha', 'A Geop Wb 100M Gha'), ('agro_wb-100m-ner', 'A Geop Wb 100M Ner')], max_length=255),
        ),
        migrations.AlterField(
            model_name='eoproduct',
            name='task_kwargs',
            field=models.JSONField(default=dict),
        ),
    ]
