# Generated by Django 3.2.5 on 2021-08-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0029_auto_20210812_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoptask',
            name='eo_product',
            field=models.ManyToManyField(null=True, related_name='task', related_query_name='task', to='eo_engine.EOProduct'),
        ),
        migrations.AddField(
            model_name='geoptask',
            name='eo_source',
            field=models.ManyToManyField(null=True, related_name='task', related_query_name='task', to='eo_engine.EOSource'),
        ),
    ]
