# Generated by Django 3.2.5 on 2021-08-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0030_auto_20210826_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geoptask',
            options={'get_latest_by': ['datetime_submitted'], 'ordering': ['datetime_submitted']},
        ),
        migrations.AlterField(
            model_name='eoproduct',
            name='status',
            field=models.CharField(choices=[('Available', 'AVAILABLE for generation.'), ('Scheduled', 'SCHEDULED For generation.'), ('Failed', 'Generation was attempted but FAILED'), ('Generating', 'GENERATING...'), ('Ignore', 'Skip generation (Ignored) .'), ('Ready', 'Product is READY.')], default='Available', max_length=255),
        ),
        migrations.AlterField(
            model_name='eosource',
            name='status',
            field=models.CharField(choices=[('availableRemotely', 'Available on the Remote Server'), ('scheduledForDownload', 'Scheduled For Download'), ('availableLocally', 'File is Available Locally'), ('beingDownloaded', 'File is Being Downloaded'), ('Ignore', 'Action on this file has been canceled (Ignored/Revoked Action)')], default='availableRemotely', max_length=255),
        ),
        migrations.AlterField(
            model_name='geoptask',
            name='eo_product',
            field=models.ManyToManyField(related_name='task', related_query_name='task', to='eo_engine.EOProduct'),
        ),
        migrations.AlterField(
            model_name='geoptask',
            name='eo_source',
            field=models.ManyToManyField(related_name='task', related_query_name='task', to='eo_engine.EOSource'),
        ),
    ]
