# Generated by Django 3.2.5 on 2021-09-27 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0032_auto_20210922_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eoproduct',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='eosource',
            old_name='status',
            new_name='state',
        ),
    ]
