# Generated by Django 3.2.7 on 2021-09-29 12:22

from django.db import migrations


def forwards_func(apps, schema_editor):
    Credentials = apps.get_model("eo_engine", "Credentials")

    Credentials.objects.bulk_create([
        Credentials(domain="safmil.ipma.pt",
                    username="rgicherif",
                    password="IFeri#97"),
    ])


def reverse_func(apps, schema_editor):
    Credentials = apps.get_model("eo_engine", "Credentials")

    db_alias = schema_editor.connection.alias
    Credentials.objects.filter(domain="safmil.ipma.pt").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0033_auto_20210927_0257'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
