# Generated by Django 3.2.7 on 2021-10-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0034_LSASAF_Products_credentials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eoproduct',
            options={'ordering': ['group', 'filename']},
        ),
        migrations.AlterModelOptions(
            name='eosource',
            options={'ordering': ['group', '-datetime_reference']},
        ),
        migrations.RenameField(
            model_name='eoproduct',
            old_name='product_group',
            new_name='group',
        ),
        migrations.RemoveField(
            model_name='eosource',
            name='product',
        ),
        migrations.AddField(
            model_name='eosource',
            name='group',
            field=models.CharField(choices=[('c_gsl_ndvi300-v2-glob', 'Copernicus Global Land Service NDVI 300m v2'), ('c_gsl_ndvi1km-v3-glob', 'Copernicus Global Land Service NDVI 1km v3'), ('a_agro_ndvi300-v3-afr', 'AuthAgro Service NDVI 1km v3'), ('c_gsl_lai300-v1-glob', 'Copernicus Global Land Service LAI 300m v1'), ('c_gls_wb100-v1-glob', 'Copernicus Global Land Service Water Bodies Collection 100m Version 1'), ('LSASAF-ET-3000M', 'LSA-SAF ET product 3Km')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
