# Generated by Django 3.2.7 on 2021-10-07 11:14

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Credentials = apps.get_model("eo_engine", "Credentials")

    Credentials.objects.bulk_create([
        Credentials(domain="WAPOR",
                    api_key='f90c385495d61b7afd7518864b57ea34097d5b12edef76e66d3abb9d859785ccb020b606edb4574d',
                    type='API-KEY')
    ])


def reverse_func(apps, schema_editor):
    Credentials = apps.get_model("eo_engine", "Credentials")

    db_alias = schema_editor.connection.alias
    Credentials.objects.filter(domain="WAPOR").delete()


class Migration(migrations.Migration):
    dependencies = [
        ('eo_engine', '0037_alter_eosource_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='api_key',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='credentials',
            name='type',
            field=models.CharField(choices=[('USER/PASS', 'USERNAME-PASSWORD'), ('API-KEY', 'API-KEY')],
                                   db_column='type', default='USER/PASS', max_length=255),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='domain',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(forwards_func, reverse_func)
    ]
