# Generated by Django 3.2.8 on 2021-10-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0041_add_wapor_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eosource',
            name='group',
            field=models.CharField(choices=[('c_gsl_ndvi300-v2-glob', 'Copernicus Global Land Service NDVI 300m v2'), ('c_gsl_ndvi1km-v3-glob', 'Copernicus Global Land Service NDVI 1km v3'), ('a_agro_ndvi300-v3-afr', 'AuthAgro Service NDVI 1km v3'), ('c_gsl_lai300-v1-glob', 'Copernicus Global Land Service LAI 300m v1'), ('c_gls_wb100-v1-glob', 'Copernicus Global Land Service Water Bodies Collection 100m Version 1'), ('WB_300m_v2_GLOB', 'Copernicus Global Land Service Water Bodies Collection 300m Version 2'), ('MSG-3km_GLOB', 'LSA-SAF Global ET product 3Km'), ('WAPOR_L1_AETI_D_AFRICA', 'WAPOR: L1 AETI D AFRICA'), ('WAPOR_L1_QUAL_LST_D_AFRICA', 'WAPOR: L1_QUAL_LST_D_AFRICA'), ('WAPOR_L1_QUAL_NDVI_D_AFRICA', 'WAPOR: L1_QUAL_NDVI_D_AFRICA'), ('WAPOR_L2_AETI_D_TUN', 'WAPOR: L2_AETI_TUN'), ('WAPOR_L2_QUAL_LST_D_TUN', 'WAPOR: L2_QUAL_LST_D_TUN'), ('WAPOR_L2_QUAL_NDVI_D_TUN', 'WAPOR: L2_QUAL_NDVI_D_TUN'), ('WAPOR_L2_AETI_D_KEN', 'WAPOR: L2_AETI_KEN'), ('WAPOR_L2_QUAL_LST_D_KEN', 'WAPOR: L2_QUAL_LST_D_KEN'), ('WAPOR_L2_QUAL_NDVI_D_KEN', 'WAPOR: L2_QUAL_NDVI_D_KEN'), ('WAPOR_L2_AETI_D_MOZ', 'WAPOR: L2_AETI_MOZ'), ('WAPOR_L2_QUAL_LST_D_MOZ', 'WAPOR: L2_QUAL_LST_D_MOZ'), ('WAPOR_L2_QUAL_NDVI_D_MOZ', 'WAPOR: L2_QUAL_NDVI_D_MOZ'), ('WAPOR_L2_AETI_D_RWA', 'WAPOR: L2_AETI__DRWA'), ('WAPOR_L2_QUAL_LST_D_RWA', 'WAPOR: L2_QUAL_LST_D_RWA'), ('WAPOR_L2_QUAL_NDVI_D_RWA', 'WAPOR: L2_QUAL_NDVI_D_RWA'), ('WAPOR_L2_AETI_D_ETH', 'WAPOR: WAPOR_L2_AETI_ETH'), ('WAPOR_L2_QUAL_LST_D_ETH', 'WAPOR: L2_QUAL_LST_D_ETH'), ('WAPOR_L2_QUAL_NDVI_D_ETH', 'WAPOR: L2_QUAL_NDVI_D_ETH'), ('WAPOR_L2_AETI_D_GHA', 'WAPOR: L2_AETI_GHA'), ('WAPOR_L2_QUAL_LST_D_GHA', 'WAPOR: L2_QUAL_LST_D_GHA'), ('WAPOR_L2_QUAL_NDVI_D_GHA', 'WAPOR: L2_QUAL_NDVI_D_GHA'), ('VIIRS-1day', 'VIIRS-1day')], max_length=255),
        ),
    ]
