# Generated by Django 3.2.8 on 2021-11-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0043_auto_20211109_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoproduct',
            name='group',
            field=models.CharField(choices=[('AGRO_NDVI_1KM_V3_AFR', 'AUTH/AGRO/NDVI 1km, V3 Africa'), ('AGRO_NDVI_300M_V3_AFR', 'AUTH/AGRO/NDVI 300m, V3 Africa'), ('AGRO_VCI_1KM_V2_AFR', 'AUTH/AGRO/VCI 1km, V2 Africa'), ('AGRO_LAI_300M_V1_AFR', 'AUTH/AGRO/LAI 300m, V1 Africa'), ('AGRO_LAI_1KM_V2_AFR', 'AUTH/AGRO/LAI 1km, V2 Africa'), ('AGRO_WB_100M_ETH', 'AGRO_WB_100_M_ETH'), ('AGRO_WB_100M_GHA', 'AGRO_WB_100_M_GHA'), ('AGRO_WB_100M_KEN', 'AGRO_WB_100_M_KEN'), ('AGRO_WB_100M_MOZ', 'AGRO_WB_100_M_MOZ'), ('AGRO_WB_100M_NER', 'AGRO_WB_100_M_NER'), ('AGRO_WB_100M_RWA', 'AGRO_WB_100_M_RWA'), ('AGRO_WB_100M_TUN', 'AGRO_WB_100_M_TUN'), ('AGRO_WB_100M_ZAF', 'AGRO_WB_100_M_ZAF'), ('AGRO_WB_300M_V2_AFR', 'Agro Wb 300M V2 Afr'), ('MSG_3KM_AFR', 'LSA-SAF 3km Africa'), ('VIIRS_1DAY_AFR', 'VIIRS 1day AFR')], max_length=255),
        ),
        migrations.AlterField(
            model_name='eosource',
            name='group',
            field=models.CharField(choices=[('C_GLS_LAI_300M_V1_GLOB', 'Copernicus Global Land Service LAI 300m v1'), ('C_GlS_NDVI_1KM_V3_GLOB', 'Copernicus Global Land Service NDVI 1km v3'), ('C_GLS_NDVI_300M_V2_GLOB', 'Copernicus Global Land Service NDVI 300m v2'), ('A_AGRO_NDVI_300M_V3_AFR', 'AuthAgro Service NDVI 300M v3'), ('A_AGRO_NDVI_1KM_V3_AFR', 'AuthAgro Service NDVU 1KM V3 Africa'), ('C_GLS_WB_100M_V1_GLOB', 'Copernicus Global Land Service Water Bodies Collection 100m Version 1'), ('WB_300M_V2_GLOB', 'Copernicus Global Land Service Water Bodies Collection 300m Version 2'), ('MSG_3KM_GLOB', 'LSA-SAF Global ET product 3Km'), ('WAPOR_L1_AETI_D_AFRICA', 'WAPOR: L1 AETI D AFRICA'), ('WAPOR_L1_QUAL_LST_D_AFRICA', 'WAPOR: L1_QUAL_LST_D_AFRICA'), ('WAPOR_L1_QUAL_NDVI_D_AFRICA', 'WAPOR: L1_QUAL_NDVI_D_AFRICA'), ('WAPOR_L2_AETI_D_TUN', 'WAPOR: L2_AETI_D_TUN'), ('WAPOR_L2_QUAL_LST_D_TUN', 'WAPOR: L2_QUAL_LST_D_TUN'), ('WAPOR_L2_QUAL_NDVI_D_TUN', 'WAPOR: L2_QUAL_NDVI_D_TUN'), ('WAPOR_L2_AETI_D_KEN', 'WAPOR: L2_AETI_D_KEN'), ('WAPOR_L2_QUAL_LST_D_KEN', 'WAPOR: L2_QUAL_LST_D_KEN'), ('WAPOR_L2_QUAL_NDVI_D_KEN', 'WAPOR: L2_QUAL_NDVI_D_KEN'), ('WAPOR_L2_AETI_D_MOZ', 'WAPOR: L2_AETI_D_MOZ'), ('WAPOR_L2_QUAL_LST_D_MOZ', 'WAPOR: L2_QUAL_LST_D_MOZ'), ('WAPOR_L2_QUAL_NDVI_D_MOZ', 'WAPOR: L2_QUAL_NDVI_D_MOZ'), ('WAPOR_L2_AETI_D_RWA', 'WAPOR: L2_AETI_D_DRWA'), ('WAPOR_L2_QUAL_LST_D_RWA', 'WAPOR: L2_QUAL_LST_D_RWA'), ('WAPOR_L2_QUAL_NDVI_D_RWA', 'WAPOR: L2_QUAL_NDVI_D_RWA'), ('WAPOR_L2_AETI_D_ETH', 'WAPOR: WAPOR_L2_AETI_D_ETH'), ('WAPOR_L2_QUAL_LST_D_ETH', 'WAPOR: L2_QUAL_LST_D_ETH'), ('WAPOR_L2_QUAL_NDVI_D_ETH', 'WAPOR: L2_QUAL_NDVI_D_ETH'), ('WAPOR_L2_AETI_D_GHA', 'WAPOR: L2_AETI_GHA'), ('WAPOR_L2_QUAL_LST_D_GHA', 'WAPOR: L2_QUAL_LST_D_GHA'), ('WAPOR_L2_QUAL_NDVI_GHA', 'WAPOR: L2_QUAL_NDVI_D_GHA'), ('VIIRS_1_DAY', 'VIIRS-1day')], max_length=255),
        ),
        migrations.AlterField(
            model_name='eosource',
            name='state',
            field=models.CharField(choices=[('availableRemotely', 'Available on the Remote Server'), ('ScheduledForDownload', 'Scheduled For Download'), ('availableLocally', 'File is Available Locally'), ('BeingDownloaded', 'Downloading File...'), ('FailedToDownload', 'Failed to Download'), ('Ignore', 'Action on this file has been canceled (Ignored/Revoked Action)'), ('Defer', 'Download has been deferred for later')], default='availableRemotely', max_length=255),
        ),
    ]
