# Generated by Django 3.2.9 on 2021-12-05 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0044_auto_20211120_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='EOSourceMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateField()),
                ('notes', models.TextField(default='')),
                ('group', models.TextField(choices=[('C_GLS_LAI_300M_V1_GLOB', 'Copernicus Global Land Service LAI 300m v1'), ('AGRO_LAI_300M_V1_AFR', 'AuthAgro LAI 300M V1'), ('C_GlS_NDVI_1KM_V3_GLOB', 'Copernicus Global Land Service NDVI 1km v3'), ('C_GLS_NDVI_300M_V2_GLOB', 'Copernicus Global Land Service NDVI 300m v2'), ('A_AGRO_NDVI_300M_V3_AFR', 'AuthAgro Service NDVI 300M v3'), ('A_AGRO_NDVI_1KM_V3_AFR', 'AuthAgro Service NDVU 1KM V3 Africa'), ('C_GLS_WB_100M_V1_GLOB', 'Copernicus Global Land Service Water Bodies Collection 100m Version 1'), ('C_GLS_WB_300M_V2_GLOB', 'Copernicus Global Land Service Water Bodies Collection 300m Version 2'), ('MSG_3KM_GLOB', 'LSA-SAF Global ET product 3Km'), ('WAPOR_L1_AETI_D_AFRICA', 'WAPOR: L1 AETI D AFRICA'), ('WAPOR_L1_QUAL_LST_D_AFRICA', 'WAPOR: L1_QUAL_LST_D_AFRICA'), ('WAPOR_L1_QUAL_NDVI_D_AFRICA', 'WAPOR: L1_QUAL_NDVI_D_AFRICA'), ('WAPOR_L2_AETI_D_TUN', 'WAPOR: L2_AETI_D_TUN'), ('WAPOR_L2_QUAL_LST_D_TUN', 'WAPOR: L2_QUAL_LST_D_TUN'), ('WAPOR_L2_QUAL_NDVI_D_TUN', 'WAPOR: L2_QUAL_NDVI_D_TUN'), ('WAPOR_L2_AETI_D_KEN', 'WAPOR: L2_AETI_D_KEN'), ('WAPOR_L2_QUAL_LST_D_KEN', 'WAPOR: L2_QUAL_LST_D_KEN'), ('WAPOR_L2_QUAL_NDVI_D_KEN', 'WAPOR: L2_QUAL_NDVI_D_KEN'), ('WAPOR_L2_AETI_D_MOZ', 'WAPOR: L2_AETI_D_MOZ'), ('WAPOR_L2_QUAL_LST_D_MOZ', 'WAPOR: L2_QUAL_LST_D_MOZ'), ('WAPOR_L2_QUAL_NDVI_D_MOZ', 'WAPOR: L2_QUAL_NDVI_D_MOZ'), ('WAPOR_L2_AETI_D_RWA', 'WAPOR: L2_AETI_D_DRWA'), ('WAPOR_L2_QUAL_LST_D_RWA', 'WAPOR: L2_QUAL_LST_D_RWA'), ('WAPOR_L2_QUAL_NDVI_D_RWA', 'WAPOR: L2_QUAL_NDVI_D_RWA'), ('WAPOR_L2_AETI_D_ETH', 'WAPOR: WAPOR_L2_AETI_D_ETH'), ('WAPOR_L2_QUAL_LST_D_ETH', 'WAPOR: L2_QUAL_LST_D_ETH'), ('WAPOR_L2_QUAL_NDVI_D_ETH', 'WAPOR: L2_QUAL_NDVI_D_ETH'), ('WAPOR_L2_AETI_D_GHA', 'WAPOR: L2_AETI_GHA'), ('WAPOR_L2_QUAL_LST_D_GHA', 'WAPOR: L2_QUAL_LST_D_GHA'), ('WAPOR_L2_QUAL_NDVI_GHA', 'WAPOR: L2_QUAL_NDVI_D_GHA'), ('FLOODLIGHT_VIIRS_1_DAY', 'VIIRS-1day'), ('GMOD09Q1_NDVI_ANOM_TUN ', 'GMOD09Q1_NDVI_ANOM_TUN '), ('GMOD09Q1_NDVI_ANOM_RWA', 'GMOD09Q1_NDVI_ANOM_RWA'), ('GMOD09Q1_NDVI_ANOM_ETH', 'GMOD09Q1_NDVI_ANOM_ETH'), ('GMOD09Q1_NDVI_ANOM_ZAF', 'GMOD09Q1_NDVI_ANOM_ZAF'), ('GMOD09Q1_NDVI_ANOM_NER', 'GMOD09Q1_NDVI_ANOM_NER'), ('GMOD09Q1_NDVI_ANOM_GHA', 'GMOD09Q1_NDVI_ANOM_GHA'), ('GMOD09Q1_NDVI_ANOM_MOZ', 'GMOD09Q1_NDVI_ANOM_MOZ'), ('GMOD09Q1_NDVI_ANOM_KEN', 'GMOD09Q1_NDVI_ANOM_KEN')], unique=True)),
                ('last_scan', models.DateTimeField(null=True)),
                ('scrape_params', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='eosource',
            name='group',
            field=models.CharField(choices=[('C_GLS_LAI_300M_V1_GLOB', 'Copernicus Global Land Service LAI 300m v1'), ('AGRO_LAI_300M_V1_AFR', 'AuthAgro LAI 300M V1'), ('C_GlS_NDVI_1KM_V3_GLOB', 'Copernicus Global Land Service NDVI 1km v3'), ('C_GLS_NDVI_300M_V2_GLOB', 'Copernicus Global Land Service NDVI 300m v2'), ('A_AGRO_NDVI_300M_V3_AFR', 'AuthAgro Service NDVI 300M v3'), ('A_AGRO_NDVI_1KM_V3_AFR', 'AuthAgro Service NDVU 1KM V3 Africa'), ('C_GLS_WB_100M_V1_GLOB', 'Copernicus Global Land Service Water Bodies Collection 100m Version 1'), ('C_GLS_WB_300M_V2_GLOB', 'Copernicus Global Land Service Water Bodies Collection 300m Version 2'), ('MSG_3KM_GLOB', 'LSA-SAF Global ET product 3Km'), ('WAPOR_L1_AETI_D_AFRICA', 'WAPOR: L1 AETI D AFRICA'), ('WAPOR_L1_QUAL_LST_D_AFRICA', 'WAPOR: L1_QUAL_LST_D_AFRICA'), ('WAPOR_L1_QUAL_NDVI_D_AFRICA', 'WAPOR: L1_QUAL_NDVI_D_AFRICA'), ('WAPOR_L2_AETI_D_TUN', 'WAPOR: L2_AETI_D_TUN'), ('WAPOR_L2_QUAL_LST_D_TUN', 'WAPOR: L2_QUAL_LST_D_TUN'), ('WAPOR_L2_QUAL_NDVI_D_TUN', 'WAPOR: L2_QUAL_NDVI_D_TUN'), ('WAPOR_L2_AETI_D_KEN', 'WAPOR: L2_AETI_D_KEN'), ('WAPOR_L2_QUAL_LST_D_KEN', 'WAPOR: L2_QUAL_LST_D_KEN'), ('WAPOR_L2_QUAL_NDVI_D_KEN', 'WAPOR: L2_QUAL_NDVI_D_KEN'), ('WAPOR_L2_AETI_D_MOZ', 'WAPOR: L2_AETI_D_MOZ'), ('WAPOR_L2_QUAL_LST_D_MOZ', 'WAPOR: L2_QUAL_LST_D_MOZ'), ('WAPOR_L2_QUAL_NDVI_D_MOZ', 'WAPOR: L2_QUAL_NDVI_D_MOZ'), ('WAPOR_L2_AETI_D_RWA', 'WAPOR: L2_AETI_D_DRWA'), ('WAPOR_L2_QUAL_LST_D_RWA', 'WAPOR: L2_QUAL_LST_D_RWA'), ('WAPOR_L2_QUAL_NDVI_D_RWA', 'WAPOR: L2_QUAL_NDVI_D_RWA'), ('WAPOR_L2_AETI_D_ETH', 'WAPOR: WAPOR_L2_AETI_D_ETH'), ('WAPOR_L2_QUAL_LST_D_ETH', 'WAPOR: L2_QUAL_LST_D_ETH'), ('WAPOR_L2_QUAL_NDVI_D_ETH', 'WAPOR: L2_QUAL_NDVI_D_ETH'), ('WAPOR_L2_AETI_D_GHA', 'WAPOR: L2_AETI_GHA'), ('WAPOR_L2_QUAL_LST_D_GHA', 'WAPOR: L2_QUAL_LST_D_GHA'), ('WAPOR_L2_QUAL_NDVI_GHA', 'WAPOR: L2_QUAL_NDVI_D_GHA'), ('FLOODLIGHT_VIIRS_1_DAY', 'VIIRS-1day'), ('GMOD09Q1_NDVI_ANOM_TUN ', 'GMOD09Q1_NDVI_ANOM_TUN '), ('GMOD09Q1_NDVI_ANOM_RWA', 'GMOD09Q1_NDVI_ANOM_RWA'), ('GMOD09Q1_NDVI_ANOM_ETH', 'GMOD09Q1_NDVI_ANOM_ETH'), ('GMOD09Q1_NDVI_ANOM_ZAF', 'GMOD09Q1_NDVI_ANOM_ZAF'), ('GMOD09Q1_NDVI_ANOM_NER', 'GMOD09Q1_NDVI_ANOM_NER'), ('GMOD09Q1_NDVI_ANOM_GHA', 'GMOD09Q1_NDVI_ANOM_GHA'), ('GMOD09Q1_NDVI_ANOM_MOZ', 'GMOD09Q1_NDVI_ANOM_MOZ'), ('GMOD09Q1_NDVI_ANOM_KEN', 'GMOD09Q1_NDVI_ANOM_KEN')], max_length=255),
        ),
        migrations.AddField(
            model_name='eosource',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eo_engine.eosourcemeta'),
        ),
    ]
