# Generated by Django 3.2.9 on 2021-12-05 18:44

from django.db import migrations
from django.utils.datetime_safe import date


def forward_code_1(apps, schema_editor):
    EOSourceMeta = apps.get_model("eo_engine", "EOSourceMeta")
    EOSource = apps.get_model("eo_engine", "EOSource")

    eo_groups = list(EOSource.objects.order_by().distinct('group').values_list('group', flat=True))
    eo_source_meta_bag = []
    for g in eo_groups:
        o = EOSourceMeta(
            group=g,
            from_date=date(2017, 1, 1)
        )
        eo_source_meta_bag.append(o)
    EOSourceMeta.objects.bulk_create(eo_source_meta_bag)


def reverse_func_1(apps, schema_editor):
    EOSourceMeta = apps.get_model("eo_engine", "EOSourceMeta")

    EOSourceMeta.objects.all().delete()


def forward_code_2(apps, schema_editor):
    EOSourceMeta = apps.get_model("eo_engine", "EOSourceMeta")
    EOSource = apps.get_model("eo_engine", "EOSource")

    eo_groups = list(EOSource.objects.order_by().distinct('group').values_list('group', flat=True))
    for g in eo_groups:
        rule = EOSourceMeta.objects.get(group=g)
        EOSource.objects.filter(group=g).update(rule=rule)


def reverse_func_2(apps, schema_editor):
    EOSourceMeta = apps.get_model("eo_engine", "EOSourceMeta")
    EOSource = apps.get_model("eo_engine", "EOSource")

    EOSource.objects.all().update(group=None)


class Migration(migrations.Migration):
    dependencies = [
        ('eo_engine', '0045_auto_20211205_1839'),
    ]

    operations = [
        migrations.RunPython(code=forward_code_1, reverse_code=reverse_func_1),
        migrations.RunPython(code=forward_code_2, reverse_code=reverse_func_2),
    ]
