# Generated by Django 3.2.9 on 2021-12-05 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eo_engine', '0047_auto_20211205_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eosourcemeta',
            name='last_scan',
        ),
    ]
