from dataclasses import dataclass
from typing import List, NamedTuple

from more_itertools import chunked

WAPORVersion = NamedTuple('WAPORVersion', [('version', int), ('label', str)])
Dimension = NamedTuple('Dimension', (('code', str), ('caption', str)))
Measure = NamedTuple('Measure', (('code', str), ('caption', str)))
Cube = NamedTuple('Cube', (('code', str), ('caption', str),
                           ('measure', List[Measure]),
                           ('dimensions', List[Dimension])))
wapor_v1 = WAPORVersion(1, 'WAPOR')
wapor_v2 = WAPORVersion(2, 'WAPOR_2')
default_wapor_version = wapor_v2
_by_twos = (lambda x: chunked(x, n=2))

cube_dimension = {
    'L1_GBWP_A': [['YEAR', 'Year']], 'L1_NBWP_A': [['YEAR', 'Year']], 'L1_AETI_A': [['YEAR', 'Year']],
    'L1_AETI_M': [['MONTH', 'Month']], 'L1_AETI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L1_T_A': [['YEAR', 'Year']], 'L1_E_A': [['YEAR', 'Year']], 'L1_I_A': [['YEAR', 'Year']],
    'L1_T_D': [['DEKAD', 'Dekad (10-Days period)']], 'L1_E_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L1_I_D': [['DEKAD', 'Dekad (10-Days period)']], 'L1_NPP_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L1_NPP_M': [['MONTH', 'Month']], 'L1_TBP_A': [['YEAR', 'Year']], 'L1_LCC_A': [['YEAR', 'Year']],
    'L1_RET_A': [['YEAR', 'Year']], 'L1_PCP_A': [['YEAR', 'Year']], 'L1_RET_M': [['MONTH', 'Month']],
    'L1_PCP_M': [['MONTH', 'Month']], 'L1_RET_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L1_PCP_D': [['DEKAD', 'Dekad (10-Days period)']], 'L1_RET_E': [['DAY', 'Day']],
    'L1_PCP_E': [['DAY', 'Day']], 'L1_QUAL_NDVI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L1_QUAL_LST_D': [['DEKAD', 'Dekad (10-Days period)']], 'L1_QUAL_NDVI_LT': [['LTP', 'Long Term']],
    'L2_GBWP_S': [['YEAR', 'Year']], 'L2_AETI_A': [['YEAR', 'Year']], 'L2_AETI_M': [['MONTH', 'Month']],
    'L2_AETI_D': [['DEKAD', 'Dekad (10-Days period)']], 'L2_T_A': [['YEAR', 'Year']],
    'L2_E_A': [['YEAR', 'Year']], 'L2_I_A': [['YEAR', 'Year']],
    'L2_T_D': [['DEKAD', 'Dekad (10-Days period)']], 'L2_E_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L2_I_D': [['DEKAD', 'Dekad (10-Days period)']], 'L2_NPP_M': [['MONTH', 'Month']],
    'L2_NPP_D': [['DEKAD', 'Dekad (10-Days period)']], 'L2_TBP_S': [['YEAR', 'Year']],
    'L2_LCC_A': [['YEAR', 'Year']], 'L2_PHE_S': [['YEAR', 'Year']],
    'L2_QUAL_NDVI_D': [['DEKAD', 'Dekad (10-Days period)']], 'L2_QUAL_NDVI_LT': [['LTP', 'Long Term']],
    'L2_QUAL_LST_D': [['DEKAD', 'Dekad (10-Days period)']], 'L2_BAS_GBWP_S': [['YEAR', 'Year']],
    'L2_CTY_GBWP_S': [['YEAR', 'Year']], 'L2_CTY_NBWP_S': [['YEAR', 'Year']],
    'L2_BAS_NBWP_S': [['YEAR', 'Year']], 'L2_BAS_AETI_A': [['YEAR', 'Year']],
    'L2_CTY_AETI_A': [['YEAR', 'Year']], 'L2_BAS_AETI_M': [['MONTH', 'Month']],
    'L2_CTY_AETI_M': [['MONTH', 'Month']], 'L2_BAS_AETI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L2_CTY_AETI_D': [['DEKAD', 'Dekad (10-Days period)']], 'L2_BAS_T_A': [['YEAR', 'Year']],
    'L2_CTY_T_A': [['YEAR', 'Year']], 'L2_BAS_E_A': [['YEAR', 'Year']], 'L2_CTY_E_A': [['YEAR', 'Year']],
    'L2_BAS_I_A': [['YEAR', 'Year']], 'L2_CTY_I_A': [['YEAR', 'Year']],
    'L2_BAS_T_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L2_CTY_T_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L2_BAS_E_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L2_CTY_E_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L2_BAS_I_D': [['DEKAD', 'Dekad (10-Days period)']], 'L2_BAS_NPP_M': [['MONTH', 'Month']],
    'L2_BAS_NPP_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L2_CTY_NPP_D': [['DEKAD', 'Dekad (10-Days period)']], 'L2_CTY_NPP_M': [['MONTH', 'Month']],
    'L2_CTY_I_D': [['DEKAD', 'Dekad (10-Days period)']], 'L2_BAS_TBP_S': [['YEAR', 'Year']],
    'L2_CTY_TBP_S': [['YEAR', 'Year']], 'L2_CTY_PHE_S': [['YEAR', 'Year']],
    'L2_BAS_LCC_A': [['YEAR', 'Year']], 'L2_CTY_LCC_A': [['YEAR', 'Year']],
    'L2_BAS_PHE_S': [['YEAR', 'Year']], 'L2_BAS_QUAL_NDVI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L2_CTY_QUAL_NDVI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L2_BAS_QUAL_LST_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L2_CTY_QUAL_LST_D': [['DEKAD', 'Dekad (10-Days period)']], 'L3_AWA_AETI_A': [['YEAR', 'Year']],
    'L3_BKA_AETI_A': [['YEAR', 'Year']], 'L3_BUS_AETI_A': [['YEAR', 'Year']],
    'L3_GEZ_AETI_A': [['YEAR', 'Year']], 'L3_KOG_AETI_A': [['YEAR', 'Year']],
    'L3_LAK_AETI_A': [['YEAR', 'Year']], 'L3_LAM_AETI_A': [['YEAR', 'Year']],
    'L3_MAL_AETI_A': [['YEAR', 'Year']], 'L3_MUV_AETI_A': [['YEAR', 'Year']],
    'L3_ODN_AETI_A': [['YEAR', 'Year']], 'L3_SED_AETI_A': [['YEAR', 'Year']],
    'L3_YAN_AETI_A': [['YEAR', 'Year']], 'L3_ZAN_AETI_A': [['YEAR', 'Year']],
    'L3_AWA_AETI_M': [['MONTH', 'Month']], 'L3_BKA_AETI_M': [['MONTH', 'Month']],
    'L3_BUS_AETI_M': [['MONTH', 'Month']], 'L3_GEZ_AETI_M': [['MONTH', 'Month']],
    'L3_KOG_AETI_M': [['MONTH', 'Month']], 'L3_LAK_AETI_M': [['MONTH', 'Month']],
    'L3_LAM_AETI_M': [['MONTH', 'Month']], 'L3_MAL_AETI_M': [['MONTH', 'Month']],
    'L3_MUV_AETI_M': [['MONTH', 'Month']], 'L3_ODN_AETI_M': [['MONTH', 'Month']],
    'L3_SED_AETI_M': [['MONTH', 'Month']], 'L3_YAN_AETI_M': [['MONTH', 'Month']],
    'L3_ZAN_AETI_M': [['MONTH', 'Month']], 'L3_AWA_AETI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_BKA_AETI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_BUS_AETI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_GEZ_AETI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_KOG_AETI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_LAK_AETI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_LAM_AETI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_MAL_AETI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_MUV_AETI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_ODN_AETI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_SED_AETI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_YAN_AETI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_ZAN_AETI_D': [['DEKAD', 'Dekad (10-Days period)']], 'L3_AWA_T_A': [['YEAR', 'Year']],
    'L3_BKA_T_A': [['YEAR', 'Year']], 'L3_BUS_T_A': [['YEAR', 'Year']], 'L3_GEZ_T_A': [['YEAR', 'Year']],
    'L3_KOG_T_A': [['YEAR', 'Year']], 'L3_LAK_T_A': [['YEAR', 'Year']], 'L3_LAM_T_A': [['YEAR', 'Year']],
    'L3_MAL_T_A': [['YEAR', 'Year']], 'L3_MUV_T_A': [['YEAR', 'Year']], 'L3_ODN_T_A': [['YEAR', 'Year']],
    'L3_SED_T_A': [['YEAR', 'Year']], 'L3_YAN_T_A': [['YEAR', 'Year']], 'L3_ZAN_T_A': [['YEAR', 'Year']],
    'L3_AWA_E_A': [['YEAR', 'Year']], 'L3_BKA_E_A': [['YEAR', 'Year']], 'L3_BUS_E_A': [['YEAR', 'Year']],
    'L3_GEZ_E_A': [['YEAR', 'Year']], 'L3_KOG_E_A': [['YEAR', 'Year']], 'L3_LAK_E_A': [['YEAR', 'Year']],
    'L3_LAM_E_A': [['YEAR', 'Year']], 'L3_MAL_E_A': [['YEAR', 'Year']], 'L3_MUV_E_A': [['YEAR', 'Year']],
    'L3_ODN_E_A': [['YEAR', 'Year']], 'L3_SED_E_A': [['YEAR', 'Year']], 'L3_YAN_E_A': [['YEAR', 'Year']],
    'L3_ZAN_E_A': [['YEAR', 'Year']], 'L3_AWA_I_A': [['YEAR', 'Year']], 'L3_BKA_I_A': [['YEAR', 'Year']],
    'L3_BUS_I_A': [['YEAR', 'Year']], 'L3_GEZ_I_A': [['YEAR', 'Year']], 'L3_KOG_I_A': [['YEAR', 'Year']],
    'L3_LAK_I_A': [['YEAR', 'Year']], 'L3_LAM_I_A': [['YEAR', 'Year']], 'L3_MAL_I_A': [['YEAR', 'Year']],
    'L3_MUV_I_A': [['YEAR', 'Year']], 'L3_ODN_I_A': [['YEAR', 'Year']], 'L3_SED_I_A': [['YEAR', 'Year']],
    'L3_YAN_I_A': [['YEAR', 'Year']], 'L3_ZAN_I_A': [['YEAR', 'Year']],
    'L3_AWA_T_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_BKA_T_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_BUS_T_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_GEZ_T_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_KOG_T_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_LAK_T_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_LAM_T_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_MAL_T_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_MUV_T_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_ODN_T_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_SED_T_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_YAN_T_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_ZAN_T_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_AWA_E_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_BKA_E_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_BUS_E_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_GEZ_E_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_KOG_E_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_LAK_E_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_LAM_E_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_MAL_E_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_MUV_E_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_ODN_E_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_SED_E_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_YAN_E_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_ZAN_E_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_AWA_I_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_BKA_I_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_BUS_I_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_GEZ_I_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_KOG_I_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_LAK_I_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_LAM_I_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_MAL_I_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_MUV_I_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_ODN_I_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_SED_I_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_YAN_I_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_ZAN_I_D': [['DEKAD', 'Dekad (10-Days period)']], 'L3_AWA_NPP_M': [['MONTH', 'Month']],
    'L3_BKA_NPP_M': [['MONTH', 'Month']], 'L3_BUS_NPP_M': [['MONTH', 'Month']],
    'L3_GEZ_NPP_M': [['MONTH', 'Month']], 'L3_KOG_NPP_M': [['MONTH', 'Month']],
    'L3_LAK_NPP_M': [['MONTH', 'Month']], 'L3_LAM_NPP_M': [['MONTH', 'Month']],
    'L3_MAL_NPP_M': [['MONTH', 'Month']], 'L3_MUV_NPP_M': [['MONTH', 'Month']],
    'L3_ODN_NPP_M': [['MONTH', 'Month']], 'L3_SED_NPP_M': [['MONTH', 'Month']],
    'L3_YAN_NPP_M': [['MONTH', 'Month']], 'L3_ZAN_NPP_M': [['MONTH', 'Month']],
    'L3_AWA_NPP_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_BKA_NPP_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_BUS_NPP_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_GEZ_NPP_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_KOG_NPP_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_LAK_NPP_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_LAM_NPP_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_MAL_NPP_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_MUV_NPP_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_ODN_NPP_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_SED_NPP_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_YAN_NPP_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_ZAN_NPP_D': [['DEKAD', 'Dekad (10-Days period)']], 'L3_AWA_TBP_S': [['YEAR', 'Year']],
    'L3_BKA_TBP_S': [['YEAR', 'Year']], 'L3_BUS_TBP_S': [['YEAR', 'Year']],
    'L3_GEZ_TBP_S': [['YEAR', 'Year']], 'L3_KOG_TBP_S': [['YEAR', 'Year']],
    'L3_LAM_TBP_S': [['YEAR', 'Year']], 'L3_MAL_TBP_S': [['YEAR', 'Year']],
    'L3_ODN_TBP_S': [['YEAR', 'Year']], 'L3_SED_TBP_S': [['YEAR', 'Year']],
    'L3_ZAN_TBP_S': [['YEAR', 'Year']], 'L3_AWA_LCC_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_BKA_LCC_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_KOG_LCC_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_ODN_LCC_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_ZAN_LCC_D': [['DEKAD', 'Dekad (10-Days period)']], 'L3_AWA_PHE_S': [['YEAR', 'Year']],
    'L3_BKA_PHE_S': [['YEAR', 'Year']], 'L3_BUS_PHE_S': [['YEAR', 'Year']],
    'L3_GEZ_PHE_S': [['YEAR', 'Year']], 'L3_KOG_PHE_S': [['YEAR', 'Year']],
    'L3_LAM_PHE_S': [['YEAR', 'Year']], 'L3_MAL_PHE_S': [['YEAR', 'Year']],
    'L3_ODN_PHE_S': [['YEAR', 'Year']], 'L3_SED_PHE_S': [['YEAR', 'Year']],
    'L3_ZAN_PHE_S': [['YEAR', 'Year']], 'L3_AWA_QUAL_LCC_S': [['YEAR', 'Year']],
    'L3_BKA_QUAL_LCC_S': [['YEAR', 'Year']], 'L3_KOG_QUAL_LCC_S': [['YEAR', 'Year']],
    'L3_ODN_QUAL_LCC_S': [['YEAR', 'Year']], 'L3_ZAN_QUAL_LCC_S': [['YEAR', 'Year']],
    'L3_AWA_QUAL_NDVI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_BKA_QUAL_NDVI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_BUS_QUAL_NDVI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_GEZ_QUAL_NDVI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_KOG_QUAL_NDVI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_LAK_QUAL_NDVI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_LAM_QUAL_NDVI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_MAL_QUAL_NDVI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_MUV_QUAL_NDVI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_ODN_QUAL_NDVI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_SED_QUAL_NDVI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_YAN_QUAL_NDVI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_ZAN_QUAL_NDVI_D': [['DEKAD', 'Dekad (10-Days period)']],
    'L3_AWA_QUAL_NDVI_LT': [['LTP', 'Long Term']], 'L3_BKA_QUAL_NDVI_LT': [['LTP', 'Long Term']],
    'L3_BUS_QUAL_NDVI_LT': [['LTP', 'Long Term']], 'L3_GEZ_QUAL_NDVI_LT': [['LTP', 'Long Term']],
    'L3_KOG_QUAL_NDVI_LT': [['LTP', 'Long Term']], 'L3_LAM_QUAL_NDVI_LT': [['LTP', 'Long Term']],
    'L3_ODN_QUAL_NDVI_LT': [['LTP', 'Long Term']], 'L3_ZAN_QUAL_NDVI_LT': [['LTP', 'Long Term']]}

cube_measures = {
    'L1_GBWP_A': [['WPR', 'Water Productivity']], 'L1_NBWP_A': [['WPR', 'Water Productivity']],
    'L1_AETI_A': [['WATER_MM', 'Amount of Water']], 'L1_AETI_M': [['WATER_MM', 'Amount of Water']],
    'L1_AETI_D': [['WATER_MM', 'Amount of Water']], 'L1_T_A': [['WATER_MM', 'Amount of Water']],
    'L1_E_A': [['WATER_MM', 'Amount of Water']], 'L1_I_A': [['WATER_MM', 'Amount of Water']],
    'L1_T_D': [['WATER_MM', 'Amount of Water']], 'L1_E_D': [['WATER_MM', 'Amount of Water']],
    'L1_I_D': [['WATER_MM', 'Amount of Water']], 'L1_NPP_D': [['NPP', 'Net Primary Production']],
    'L1_NPP_M': [['NPP', 'Net Primary Production']], 'L1_TBP_A': [['LPR', 'Land Productivity']],
    'L1_LCC_A': [['LCC', 'Land Cover Classification']], 'L1_RET_A': [['WATER_MM', 'Amount of Water']],
    'L1_PCP_A': [['WATER_MM', 'Amount of Water']], 'L1_RET_M': [['WATER_MM', 'Amount of Water']],
    'L1_PCP_M': [['WATER_MM', 'Amount of Water']], 'L1_RET_D': [['WATER_MM', 'Amount of Water']],
    'L1_PCP_D': [['WATER_MM', 'Amount of Water']], 'L1_RET_E': [['WATER_MM', 'Amount of Water']],
    'L1_PCP_E': [['WATER_MM', 'Amount of Water']], 'L1_QUAL_NDVI_D': [['N_DEKADS', 'Number of Dekads']],
    'L1_QUAL_LST_D': [['N_DAYS', 'Number of Days']], 'L1_QUAL_NDVI_LT': [['ACC', 'Accuracy']],
    'L2_GBWP_S': [['WPR', 'Water Productivity']], 'L2_AETI_A': [['WATER_MM', 'Amount of Water']],
    'L2_AETI_M': [['WATER_MM', 'Amount of Water']], 'L2_AETI_D': [['WATER_MM', 'Amount of Water']],
    'L2_T_A': [['WATER_MM', 'Amount of Water']], 'L2_E_A': [['WATER_MM', 'Amount of Water']],
    'L2_I_A': [['WATER_MM', 'Amount of Water']], 'L2_T_D': [['WATER_MM', 'Amount of Water']],
    'L2_E_D': [['WATER_MM', 'Amount of Water']], 'L2_I_D': [['WATER_MM', 'Amount of Water']],
    'L2_NPP_M': [['NPP', 'Net Primary Production']], 'L2_NPP_D': [['NPP', 'Net Primary Production']],
    'L2_TBP_S': [['LPR_S', 'Land Productivity (Seasonal)']],
    'L2_LCC_A': [['LCC', 'Land Cover Classification']], 'L2_PHE_S': [['PHE', 'Phenology']],
    'L2_QUAL_NDVI_D': [['N_DEKADS', 'Number of Dekads']], 'L2_QUAL_NDVI_LT': [['ACC', 'Accuracy']],
    'L2_QUAL_LST_D': [['N_DAYS', 'Number of Days']], 'L2_BAS_GBWP_S': [['WPR', 'Water Productivity']],
    'L2_CTY_GBWP_S': [['WPR', 'Water Productivity']], 'L2_CTY_NBWP_S': [['WPR', 'Water Productivity']],
    'L2_BAS_NBWP_S': [['WPR', 'Water Productivity']], 'L2_BAS_AETI_A': [['WATER_MM', 'Amount of Water']],
    'L2_CTY_AETI_A': [['WATER_MM', 'Amount of Water']], 'L2_BAS_AETI_M': [['WATER_MM', 'Amount of Water']],
    'L2_CTY_AETI_M': [['WATER_MM', 'Amount of Water']], 'L2_BAS_AETI_D': [['WATER_MM', 'Amount of Water']],
    'L2_CTY_AETI_D': [['WATER_MM', 'Amount of Water']], 'L2_BAS_T_A': [['WATER_MM', 'Amount of Water']],
    'L2_CTY_T_A': [['WATER_MM', 'Amount of Water']], 'L2_BAS_E_A': [['WATER_MM', 'Amount of Water']],
    'L2_CTY_E_A': [['WATER_MM', 'Amount of Water']], 'L2_BAS_I_A': [['WATER_MM', 'Amount of Water']],
    'L2_CTY_I_A': [['WATER_MM', 'Amount of Water']], 'L2_BAS_T_D': [['WATER_MM', 'Amount of Water']],
    'L2_CTY_T_D': [['WATER_MM', 'Amount of Water']], 'L2_BAS_E_D': [['WATER_MM', 'Amount of Water']],
    'L2_CTY_E_D': [['WATER_MM', 'Amount of Water']], 'L2_BAS_I_D': [['WATER_MM', 'Amount of Water']],
    'L2_BAS_NPP_M': [['NPP', 'Net Primary Production']],
    'L2_BAS_NPP_D': [['NPP', 'Net Primary Production']],
    'L2_CTY_NPP_D': [['NPP', 'Net Primary Production']],
    'L2_CTY_NPP_M': [['NPP', 'Net Primary Production']], 'L2_CTY_I_D': [['WATER_MM', 'Amount of Water']],
    'L2_BAS_TBP_S': [['LPR_S', 'Land Productivity (Seasonal)']],
    'L2_CTY_TBP_S': [['LPR_S', 'Land Productivity (Seasonal)']], 'L2_CTY_PHE_S': [['PHE', 'Phenology']],
    'L2_BAS_LCC_A': [['LCC', 'Land Cover Classification']],
    'L2_CTY_LCC_A': [['LCC', 'Land Cover Classification']], 'L2_BAS_PHE_S': [['PHE', 'Phenology']],
    'L2_BAS_QUAL_NDVI_D': [['N_DAYS', 'Number of Days']],
    'L2_CTY_QUAL_NDVI_D': [['N_DAYS', 'Number of Days']],
    'L2_BAS_QUAL_LST_D': [['N_DAYS', 'Number of Days']],
    'L2_CTY_QUAL_LST_D': [['N_DAYS', 'Number of Days']],
    'L3_AWA_AETI_A': [['WATER_MM', 'Amount of Water']], 'L3_BKA_AETI_A': [['WATER_MM', 'Amount of Water']],
    'L3_BUS_AETI_A': [['WATER_MM', 'Amount of Water']], 'L3_GEZ_AETI_A': [['WATER_MM', 'Amount of Water']],
    'L3_KOG_AETI_A': [['WATER_MM', 'Amount of Water']], 'L3_LAK_AETI_A': [['WATER_MM', 'Amount of Water']],
    'L3_LAM_AETI_A': [['WATER_MM', 'Amount of Water']], 'L3_MAL_AETI_A': [['WATER_MM', 'Amount of Water']],
    'L3_MUV_AETI_A': [['WATER_MM', 'Amount of Water']], 'L3_ODN_AETI_A': [['WATER_MM', 'Amount of Water']],
    'L3_SED_AETI_A': [['WATER_MM', 'Amount of Water']], 'L3_YAN_AETI_A': [['WATER_MM', 'Amount of Water']],
    'L3_ZAN_AETI_A': [['WATER_MM', 'Amount of Water']], 'L3_AWA_AETI_M': [['WATER_MM', 'Amount of Water']],
    'L3_BKA_AETI_M': [['WATER_MM', 'Amount of Water']], 'L3_BUS_AETI_M': [['WATER_MM', 'Amount of Water']],
    'L3_GEZ_AETI_M': [['WATER_MM', 'Amount of Water']], 'L3_KOG_AETI_M': [['WATER_MM', 'Amount of Water']],
    'L3_LAK_AETI_M': [['WATER_MM', 'Amount of Water']], 'L3_LAM_AETI_M': [['WATER_MM', 'Amount of Water']],
    'L3_MAL_AETI_M': [['WATER_MM', 'Amount of Water']], 'L3_MUV_AETI_M': [['WATER_MM', 'Amount of Water']],
    'L3_ODN_AETI_M': [['WATER_MM', 'Amount of Water']], 'L3_SED_AETI_M': [['WATER_MM', 'Amount of Water']],
    'L3_YAN_AETI_M': [['WATER_MM', 'Amount of Water']], 'L3_ZAN_AETI_M': [['WATER_MM', 'Amount of Water']],
    'L3_AWA_AETI_D': [['WATER_MM', 'Amount of Water']], 'L3_BKA_AETI_D': [['WATER_MM', 'Amount of Water']],
    'L3_BUS_AETI_D': [['WATER_MM', 'Amount of Water']], 'L3_GEZ_AETI_D': [['WATER_MM', 'Amount of Water']],
    'L3_KOG_AETI_D': [['WATER_MM', 'Amount of Water']], 'L3_LAK_AETI_D': [['WATER_MM', 'Amount of Water']],
    'L3_LAM_AETI_D': [['WATER_MM', 'Amount of Water']], 'L3_MAL_AETI_D': [['WATER_MM', 'Amount of Water']],
    'L3_MUV_AETI_D': [['WATER_MM', 'Amount of Water']], 'L3_ODN_AETI_D': [['WATER_MM', 'Amount of Water']],
    'L3_SED_AETI_D': [['WATER_MM', 'Amount of Water']], 'L3_YAN_AETI_D': [['WATER_MM', 'Amount of Water']],
    'L3_ZAN_AETI_D': [['WATER_MM', 'Amount of Water']], 'L3_AWA_T_A': [['WATER_MM', 'Amount of Water']],
    'L3_BKA_T_A': [['WATER_MM', 'Amount of Water']], 'L3_BUS_T_A': [['WATER_MM', 'Amount of Water']],
    'L3_GEZ_T_A': [['WATER_MM', 'Amount of Water']], 'L3_KOG_T_A': [['WATER_MM', 'Amount of Water']],
    'L3_LAK_T_A': [['WATER_MM', 'Amount of Water']], 'L3_LAM_T_A': [['WATER_MM', 'Amount of Water']],
    'L3_MAL_T_A': [['WATER_MM', 'Amount of Water']], 'L3_MUV_T_A': [['WATER_MM', 'Amount of Water']],
    'L3_ODN_T_A': [['WATER_MM', 'Amount of Water']], 'L3_SED_T_A': [['WATER_MM', 'Amount of Water']],
    'L3_YAN_T_A': [['WATER_MM', 'Amount of Water']], 'L3_ZAN_T_A': [['WATER_MM', 'Amount of Water']],
    'L3_AWA_E_A': [['WATER_MM', 'Amount of Water']], 'L3_BKA_E_A': [['WATER_MM', 'Amount of Water']],
    'L3_BUS_E_A': [['WATER_MM', 'Amount of Water']], 'L3_GEZ_E_A': [['WATER_MM', 'Amount of Water']],
    'L3_KOG_E_A': [['WATER_MM', 'Amount of Water']], 'L3_LAK_E_A': [['WATER_MM', 'Amount of Water']],
    'L3_LAM_E_A': [['WATER_MM', 'Amount of Water']], 'L3_MAL_E_A': [['WATER_MM', 'Amount of Water']],
    'L3_MUV_E_A': [['WATER_MM', 'Amount of Water']], 'L3_ODN_E_A': [['WATER_MM', 'Amount of Water']],
    'L3_SED_E_A': [['WATER_MM', 'Amount of Water']], 'L3_YAN_E_A': [['WATER_MM', 'Amount of Water']],
    'L3_ZAN_E_A': [['WATER_MM', 'Amount of Water']], 'L3_AWA_I_A': [['WATER_MM', 'Amount of Water']],
    'L3_BKA_I_A': [['WATER_MM', 'Amount of Water']], 'L3_BUS_I_A': [['WATER_MM', 'Amount of Water']],
    'L3_GEZ_I_A': [['WATER_MM', 'Amount of Water']], 'L3_KOG_I_A': [['WATER_MM', 'Amount of Water']],
    'L3_LAK_I_A': [['WATER_MM', 'Amount of Water']], 'L3_LAM_I_A': [['WATER_MM', 'Amount of Water']],
    'L3_MAL_I_A': [['WATER_MM', 'Amount of Water']], 'L3_MUV_I_A': [['WATER_MM', 'Amount of Water']],
    'L3_ODN_I_A': [['WATER_MM', 'Amount of Water']], 'L3_SED_I_A': [['WATER_MM', 'Amount of Water']],
    'L3_YAN_I_A': [['WATER_MM', 'Amount of Water']], 'L3_ZAN_I_A': [['WATER_MM', 'Amount of Water']],
    'L3_AWA_T_D': [['WATER_MM', 'Amount of Water']], 'L3_BKA_T_D': [['WATER_MM', 'Amount of Water']],
    'L3_BUS_T_D': [['WATER_MM', 'Amount of Water']], 'L3_GEZ_T_D': [['WATER_MM', 'Amount of Water']],
    'L3_KOG_T_D': [['WATER_MM', 'Amount of Water']], 'L3_LAK_T_D': [['WATER_MM', 'Amount of Water']],
    'L3_LAM_T_D': [['WATER_MM', 'Amount of Water']], 'L3_MAL_T_D': [['WATER_MM', 'Amount of Water']],
    'L3_MUV_T_D': [['WATER_MM', 'Amount of Water']], 'L3_ODN_T_D': [['WATER_MM', 'Amount of Water']],
    'L3_SED_T_D': [['WATER_MM', 'Amount of Water']], 'L3_YAN_T_D': [['WATER_MM', 'Amount of Water']],
    'L3_ZAN_T_D': [['WATER_MM', 'Amount of Water']], 'L3_AWA_E_D': [['WATER_MM', 'Amount of Water']],
    'L3_BKA_E_D': [['WATER_MM', 'Amount of Water']], 'L3_BUS_E_D': [['WATER_MM', 'Amount of Water']],
    'L3_GEZ_E_D': [['WATER_MM', 'Amount of Water']], 'L3_KOG_E_D': [['WATER_MM', 'Amount of Water']],
    'L3_LAK_E_D': [['WATER_MM', 'Amount of Water']], 'L3_LAM_E_D': [['WATER_MM', 'Amount of Water']],
    'L3_MAL_E_D': [['WATER_MM', 'Amount of Water']], 'L3_MUV_E_D': [['WATER_MM', 'Amount of Water']],
    'L3_ODN_E_D': [['WATER_MM', 'Amount of Water']], 'L3_SED_E_D': [['WATER_MM', 'Amount of Water']],
    'L3_YAN_E_D': [['WATER_MM', 'Amount of Water']], 'L3_ZAN_E_D': [['WATER_MM', 'Amount of Water']],
    'L3_AWA_I_D': [['WATER_MM', 'Amount of Water']], 'L3_BKA_I_D': [['WATER_MM', 'Amount of Water']],
    'L3_BUS_I_D': [['WATER_MM', 'Amount of Water']], 'L3_GEZ_I_D': [['WATER_MM', 'Amount of Water']],
    'L3_KOG_I_D': [['WATER_MM', 'Amount of Water']], 'L3_LAK_I_D': [['WATER_MM', 'Amount of Water']],
    'L3_LAM_I_D': [['WATER_MM', 'Amount of Water']], 'L3_MAL_I_D': [['WATER_MM', 'Amount of Water']],
    'L3_MUV_I_D': [['WATER_MM', 'Amount of Water']], 'L3_ODN_I_D': [['WATER_MM', 'Amount of Water']],
    'L3_SED_I_D': [['WATER_MM', 'Amount of Water']], 'L3_YAN_I_D': [['WATER_MM', 'Amount of Water']],
    'L3_ZAN_I_D': [['WATER_MM', 'Amount of Water']], 'L3_AWA_NPP_M': [['NPP', 'Net Primary Production']],
    'L3_BKA_NPP_M': [['NPP', 'Net Primary Production']],
    'L3_BUS_NPP_M': [['NPP', 'Net Primary Production']],
    'L3_GEZ_NPP_M': [['NPP', 'Net Primary Production']],
    'L3_KOG_NPP_M': [['NPP', 'Net Primary Production']],
    'L3_LAK_NPP_M': [['NPP', 'Net Primary Production']],
    'L3_LAM_NPP_M': [['NPP', 'Net Primary Production']],
    'L3_MAL_NPP_M': [['NPP', 'Net Primary Production']],
    'L3_MUV_NPP_M': [['NPP', 'Net Primary Production']],
    'L3_ODN_NPP_M': [['NPP', 'Net Primary Production']],
    'L3_SED_NPP_M': [['NPP', 'Net Primary Production']],
    'L3_YAN_NPP_M': [['NPP', 'Net Primary Production']],
    'L3_ZAN_NPP_M': [['NPP', 'Net Primary Production']],
    'L3_AWA_NPP_D': [['NPP', 'Net Primary Production']],
    'L3_BKA_NPP_D': [['NPP', 'Net Primary Production']],
    'L3_BUS_NPP_D': [['NPP', 'Net Primary Production']],
    'L3_GEZ_NPP_D': [['NPP', 'Net Primary Production']],
    'L3_KOG_NPP_D': [['NPP', 'Net Primary Production']],
    'L3_LAK_NPP_D': [['NPP', 'Net Primary Production']],
    'L3_LAM_NPP_D': [['NPP', 'Net Primary Production']],
    'L3_MAL_NPP_D': [['NPP', 'Net Primary Production']],
    'L3_MUV_NPP_D': [['NPP', 'Net Primary Production']],
    'L3_ODN_NPP_D': [['NPP', 'Net Primary Production']],
    'L3_SED_NPP_D': [['NPP', 'Net Primary Production']],
    'L3_YAN_NPP_D': [['NPP', 'Net Primary Production']],
    'L3_ZAN_NPP_D': [['NPP', 'Net Primary Production']],
    'L3_AWA_TBP_S': [['LPR_S', 'Land Productivity (Seasonal)']],
    'L3_BKA_TBP_S': [['LPR_S', 'Land Productivity (Seasonal)']],
    'L3_BUS_TBP_S': [['LPR_S', 'Land Productivity (Seasonal)']],
    'L3_GEZ_TBP_S': [['LPR_S', 'Land Productivity (Seasonal)']],
    'L3_KOG_TBP_S': [['LPR_S', 'Land Productivity (Seasonal)']],
    'L3_LAM_TBP_S': [['LPR_S', 'Land Productivity (Seasonal)']],
    'L3_MAL_TBP_S': [['LPR_S', 'Land Productivity (Seasonal)']],
    'L3_ODN_TBP_S': [['LPR_S', 'Land Productivity (Seasonal)']],
    'L3_SED_TBP_S': [['LPR_S', 'Land Productivity (Seasonal)']],
    'L3_ZAN_TBP_S': [['LPR_S', 'Land Productivity (Seasonal)']],
    'L3_AWA_LCC_D': [['L3_AWA_LCC', 'Land Cover Classification']],
    'L3_BKA_LCC_D': [['L3_BKA_LCC', 'Land Cover Classification']],
    'L3_KOG_LCC_D': [['L3_KOG_LCC', 'Land Cover Classification']],
    'L3_ODN_LCC_D': [['L3_ODN_LCC', 'Land Cover Classification']],
    'L3_ZAN_LCC_D': [['L3_ZAN_LCC', 'Land Cover Classification']], 'L3_AWA_PHE_S': [['PHE', 'Phenology']],
    'L3_BKA_PHE_S': [['PHE', 'Phenology']], 'L3_BUS_PHE_S': [['PHE', 'Phenology']],
    'L3_GEZ_PHE_S': [['PHE', 'Phenology']], 'L3_KOG_PHE_S': [['PHE', 'Phenology']],
    'L3_LAM_PHE_S': [['PHE', 'Phenology']], 'L3_MAL_PHE_S': [['PHE', 'Phenology']],
    'L3_ODN_PHE_S': [['PHE', 'Phenology']], 'L3_SED_PHE_S': [['PHE', 'Phenology']],
    'L3_ZAN_PHE_S': [['PHE', 'Phenology']], 'L3_AWA_QUAL_LCC_S': [['ACC', 'Accuracy']],
    'L3_BKA_QUAL_LCC_S': [['ACC', 'Accuracy']], 'L3_KOG_QUAL_LCC_S': [['ACC', 'Accuracy']],
    'L3_ODN_QUAL_LCC_S': [['ACC', 'Accuracy']], 'L3_ZAN_QUAL_LCC_S': [['ACC', 'Accuracy']],
    'L3_AWA_QUAL_NDVI_D': [['N_DEKADS', 'Number of Dekads']],
    'L3_BKA_QUAL_NDVI_D': [['N_DEKADS', 'Number of Dekads']],
    'L3_BUS_QUAL_NDVI_D': [['N_DEKADS', 'Number of Dekads']],
    'L3_GEZ_QUAL_NDVI_D': [['N_DEKADS', 'Number of Dekads']],
    'L3_KOG_QUAL_NDVI_D': [['N_DEKADS', 'Number of Dekads']],
    'L3_LAK_QUAL_NDVI_D': [['N_DEKADS', 'Number of Dekads']],
    'L3_LAM_QUAL_NDVI_D': [['N_DEKADS', 'Number of Dekads']],
    'L3_MAL_QUAL_NDVI_D': [['N_DEKADS', 'Number of Dekads']],
    'L3_MUV_QUAL_NDVI_D': [['N_DEKADS', 'Number of Dekads']],
    'L3_ODN_QUAL_NDVI_D': [['N_DEKADS', 'Number of Dekads']],
    'L3_SED_QUAL_NDVI_D': [['N_DEKADS', 'Number of Dekads']],
    'L3_YAN_QUAL_NDVI_D': [['N_DEKADS', 'Number of Dekads']],
    'L3_ZAN_QUAL_NDVI_D': [['N_DEKADS', 'Number of Dekads']], 'L3_AWA_QUAL_NDVI_LT': [['ACC', 'Accuracy']],
    'L3_BKA_QUAL_NDVI_LT': [['ACC', 'Accuracy']], 'L3_BUS_QUAL_NDVI_LT': [['ACC', 'Accuracy']],
    'L3_GEZ_QUAL_NDVI_LT': [['ACC', 'Accuracy']], 'L3_KOG_QUAL_NDVI_LT': [['ACC', 'Accuracy']],
    'L3_LAM_QUAL_NDVI_LT': [['ACC', 'Accuracy']], 'L3_ODN_QUAL_NDVI_LT': [['ACC', 'Accuracy']],
    'L3_ZAN_QUAL_NDVI_LT': [['ACC', 'Accuracy']]}

cubes: List[Cube] = [
    Cube(
        code=code,
        caption=description,
        dimensions=[Dimension(*v) for v in cube_dimension[code]],
        measure=[Measure(*v) for v in cube_measures[code]]
    )
    for code, description in _by_twos([
        "L1_GBWP_A",
        "Gross Biomass Water Productivity",
        "L1_NBWP_A",
        "Net Biomass Water Productivity",
        "L1_AETI_A",
        "Actual EvapoTranspiration and Interception (Annual)",
        "L1_AETI_M",
        "Actual EvapoTranspiration and Interception (Monthly)",
        "L1_AETI_D",
        "Actual EvapoTranspiration and Interception (Dekadal)",
        "L1_T_A",
        "Transpiration (Annual)",
        "L1_E_A",
        "Evaporation (Annual)",
        "L1_I_A",
        "Interception (Annual)",
        "L1_T_D",
        "Transpiration (Dekadal)",
        "L1_E_D",
        "Evaporation (Dekadal)",
        "L1_I_D",
        "Interception (Dekadal)",
        "L1_NPP_D",
        "Net Primary Production (Dekadal)",
        "L1_NPP_M",
        "Net Primary Production (Monthly)",
        "L1_TBP_A",
        "Total Biomass Production (Annual)",
        "L1_LCC_A",
        "Land Cover Classification",
        "L1_RET_A",
        "Reference EvapoTranspiration (Annual)",
        "L1_PCP_A",
        "Precipitation (Annual)",
        "L1_RET_M",
        "Reference EvapoTranspiration (Monthly)",
        "L1_PCP_M",
        "Precipitation (Monthly)",
        "L1_RET_D",
        "Reference EvapoTranspiration (Dekadal)",
        "L1_PCP_D",
        "Precipitation (Dekadal)",
        "L1_RET_E",
        "Reference EvapoTranspiration (Daily)",
        "L1_PCP_E",
        "Precipitation (Daily)",
        "L1_QUAL_NDVI_D",
        "Quality of Normalized Difference Vegetation Index (Dekadal)",
        "L1_QUAL_LST_D",
        "Quality Land Surface Temperature (Dekadal)",
        "L1_QUAL_NDVI_LT",
        "Quality of Normalized Difference Vegetation Index (Long Term)",
        "L2_GBWP_S",
        "Gross Biomass Water Productivity (Seasonal)",
        "L2_AETI_A",
        "Actual EvapoTranspiration and Interception (Annual)",
        "L2_AETI_M",
        "Actual EvapoTranspiration and Interception (Monthly)",
        "L2_AETI_D",
        "Actual EvapoTranspiration and Interception (Dekadal)",
        "L2_T_A",
        "Transpiration (Annual)",
        "L2_E_A",
        "Evaporation (Annual)",
        "L2_I_A",
        "Interception (Annual)",
        "L2_T_D",
        "Transpiration (Dekadal)",
        "L2_E_D",
        "Evaporation (Dekadal)",
        "L2_I_D",
        "Interception (Dekadal)",
        "L2_NPP_M",
        "Net Primary Production (Monthly)",
        "L2_NPP_D",
        "Net Primary Production (Dekadal)",
        "L2_TBP_S",
        "Total Biomass Production (Seasonal)",
        "L2_LCC_A",
        "Land Cover Classification",
        "L2_PHE_S",
        "Phenology (Seasonal)",
        "L2_QUAL_NDVI_D",
        "Quality of Normalized Difference Vegetation Index (Dekadal)",
        "L2_QUAL_NDVI_LT",
        "Quality of Normalized Difference Vegetation Index (Long Term)",
        "L2_QUAL_LST_D",
        "Quality Land Surface Temperature (Dekadal)",
        "L2_BAS_GBWP_S",
        "Gross Biomass Water Productivity (Seasonal, clipped by basin)",
        "L2_CTY_GBWP_S",
        "Gross Biomass Water Productivity (Seasonal, clipped by country)",
        "L2_CTY_NBWP_S",
        "Net Biomass Water Productivity (Seasonal, clipped by country)",
        "L2_BAS_NBWP_S",
        "Net Biomass Water Productivity (Seasonal, clipped by basin)",
        "L2_BAS_AETI_A",
        "Actual EvapoTranspiration and Interception (Annual, clipped by basin)",
        "L2_CTY_AETI_A",
        "Actual EvapoTranspiration and Interception (Annual, clipped by country)",
        "L2_BAS_AETI_M",
        "Actual EvapoTranspiration and Interception (Monthly, clipped by basin)",
        "L2_CTY_AETI_M",
        "Actual EvapoTranspiration and Interception (Monthly, clipped by country)",
        "L2_BAS_AETI_D",
        "Actual EvapoTranspiration and Interception (Dekadal, clipped by basin)",
        "L2_CTY_AETI_D",
        "Actual EvapoTranspiration and Interception (Dekadal, clipped by country)",
        "L2_BAS_T_A",
        "Transpiration (Annual, clipped by basin)",
        "L2_CTY_T_A",
        "Transpiration (Annual, clipped by country)",
        "L2_BAS_E_A",
        "Evaporation (Annual, clipped by basin)",
        "L2_CTY_E_A",
        "Evaporation (Annual, clipped by country)",
        "L2_BAS_I_A",
        "Interception (Annual, clipped by basin)",
        "L2_CTY_I_A",
        "Interception (Annual, clipped by country)",
        "L2_BAS_T_D",
        "Transpiration (Dekadal, clipped by basin)",
        "L2_CTY_T_D",
        "Transpiration (Dekadal, clipped by country)",
        "L2_BAS_E_D",
        "Evaporation (Dekadal, clipped by basin)",
        "L2_CTY_E_D",
        "Evaporation (Dekadal, clipped by country)",
        "L2_BAS_I_D",
        "Interception (Dekadal, clipped by basin)",
        "L2_BAS_NPP_M",
        "Net Primary Production (Monthly, clipped by basin)",
        "L2_BAS_NPP_D",
        "Net Primary Production (Dekadal, clipped by basin)",
        "L2_CTY_NPP_D",
        "Net Primary Production (Dekadal, clipped by country)",
        "L2_CTY_NPP_M",
        "Net Primary Production (Monthly, clipped by country)",
        "L2_CTY_I_D",
        "Interception (Dekadal, clipped by country)",
        "L2_BAS_TBP_S",
        "Total Biomass Production (Seasonal, clipped by basin)",
        "L2_CTY_TBP_S",
        "Total Biomass Production (Seasonal, clipped by country)",
        "L2_CTY_PHE_S",
        "Phenology (Seasonal, clipped by country)",
        "L2_BAS_LCC_A",
        "Land Cover Classification (Annual, clipped by basin)",
        "L2_CTY_LCC_A",
        "Land Cover Classification (Annual, clipped by country)",
        "L2_BAS_PHE_S",
        "Phenology (Seasonal, clipped by basin)",
        "L2_BAS_QUAL_NDVI_D",
        "Quality of Normalized Difference Vegetation Index (Dekadal, clipped by basin)",
        "L2_CTY_QUAL_NDVI_D",
        "Quality of Normalized Difference Vegetation Index (Dekadal, clipped by country)",
        "L2_BAS_QUAL_LST_D",
        "Quality Land Surface Temperature (Dekadal, clipped by basin)",
        "L2_CTY_QUAL_LST_D",
        "Quality Land Surface Temperature (Dekadal, clipped by country)",
        "L3_AWA_AETI_A",
        "Actual EvapoTranspiration and Interception (Awash, Ethiopia - Annual)",
        "L3_BKA_AETI_A",
        "Actual EvapoTranspiration and Interception (Bekaa, Lebanon - Annual)",
        "L3_BUS_AETI_A",
        "Actual EvapoTranspiration and Interception (Busia, Kenya - Annual)",
        "L3_GEZ_AETI_A",
        "Actual EvapoTranspiration and Interception (Gezira, Sudan - Annual)",
        "L3_KOG_AETI_A",
        "Actual EvapoTranspiration and Interception (Koga, Ethiopia - Annual)",
        "L3_LAK_AETI_A",
        "Actual EvapoTranspiration and Interception (Lower Akagera, Rwanda - Annual)",
        "L3_LAM_AETI_A",
        "Actual EvapoTranspiration and Interception (Lamego, Mozambique - Annual)",
        "L3_MAL_AETI_A",
        "Actual EvapoTranspiration and Interception (Malwathu Oya West Sub Catchment, Sri Lanka - Annual)",
        "L3_MUV_AETI_A",
        "Actual EvapoTranspiration and Interception (Muvumba catchment, Rwanda - Annual)",
        "L3_ODN_AETI_A",
        "Actual EvapoTranspiration and Interception (Office du Niger, Mali - Annual)",
        "L3_SED_AETI_A",
        "Actual EvapoTranspiration and Interception (Senegal Delta, Senegal - Annual)",
        "L3_YAN_AETI_A",
        "Actual EvapoTranspiration and Interception (Yanze catchment, Rwanda - Annual)",
        "L3_ZAN_AETI_A",
        "Actual EvapoTranspiration and Interception (Zankalon, Egypt - Annual)",
        "L3_AWA_AETI_M",
        "Actual EvapoTranspiration and Interception (Awash, Ethiopia - Monthly)",
        "L3_BKA_AETI_M",
        "Actual EvapoTranspiration and Interception (Bekaa, Lebanon - Monthly)",
        "L3_BUS_AETI_M",
        "Actual EvapoTranspiration and Interception (Busia, Kenya - Monthly)",
        "L3_GEZ_AETI_M",
        "Actual EvapoTranspiration and Interception (Gezira, Sudan - Monthly)",
        "L3_KOG_AETI_M",
        "Actual EvapoTranspiration and Interception (Koga, Ethiopia - Monthly)",
        "L3_LAK_AETI_M",
        "Actual EvapoTranspiration and Interception (Lower Akagera, Rwanda - Monthly)",
        "L3_LAM_AETI_M",
        "Actual EvapoTranspiration and Interception (Lamego, Mozambique - Monthly)",
        "L3_MAL_AETI_M",
        "Actual EvapoTranspiration and Interception (Malwathu Oya West Sub Catchment, Sri Lanka - Monthly)",
        "L3_MUV_AETI_M",
        "Actual EvapoTranspiration and Interception (Muvumba catchment, Rwanda - Monthly)",
        "L3_ODN_AETI_M",
        "Actual EvapoTranspiration and Interception (Office du Niger, Mali - Monthly)",
        "L3_SED_AETI_M",
        "Actual EvapoTranspiration and Interception (Senegal Delta, Senegal - Monthly)",
        "L3_YAN_AETI_M",
        "Actual EvapoTranspiration and Interception (Yanze catchment, Rwanda - Monthly)",
        "L3_ZAN_AETI_M",
        "Actual EvapoTranspiration and Interception (Zankalon, Egypt - Monthly)",
        "L3_AWA_AETI_D",
        "Actual EvapoTranspiration and Interception (Awash, Ethiopia - Dekadal)",
        "L3_BKA_AETI_D",
        "Actual EvapoTranspiration and Interception (Bekaa, Lebanon - Dekadal)",
        "L3_BUS_AETI_D",
        "Actual EvapoTranspiration and Interception (Busia, Kenya - Dekadal)",
        "L3_GEZ_AETI_D",
        "Actual EvapoTranspiration and Interception (Gezira, Sudan - Dekadal)",
        "L3_KOG_AETI_D",
        "Actual EvapoTranspiration and Interception (Koga, Ethiopia - Dekadal)",
        "L3_LAK_AETI_D",
        "Actual EvapoTranspiration and Interception (Lower Akagera, Rwanda - Dekadal)",
        "L3_LAM_AETI_D",
        "Actual EvapoTranspiration and Interception (Lamego, Mozambique - Dekadal)",
        "L3_MAL_AETI_D",
        "Actual EvapoTranspiration and Interception (Malwathu Oya West Sub Catchment, Sri Lanka - Dekadal)",
        "L3_MUV_AETI_D",
        "Actual EvapoTranspiration and Interception (Muvumba catchment, Rwanda - Dekadal)",
        "L3_ODN_AETI_D",
        "Actual EvapoTranspiration and Interception (Office du Niger, Mali - Dekadal)",
        "L3_SED_AETI_D",
        "Actual EvapoTranspiration and Interception (Senegal Delta, Senegal - Dekadal)",
        "L3_YAN_AETI_D",
        "Actual EvapoTranspiration and Interception (Yanze catchment, Rwanda - Dekadal)",
        "L3_ZAN_AETI_D",
        "Actual EvapoTranspiration and Interception (Zankalon, Egypt - Dekadal)",
        "L3_AWA_T_A",
        "Transpiration (Awash, Ethiopia - Annual)",
        "L3_BKA_T_A",
        "Transpiration (Bekaa, Lebanon - Annual)",
        "L3_BUS_T_A",
        "Transpiration (Busia, Kenya - Annual)",
        "L3_GEZ_T_A",
        "Transpiration (Gezira, Sudan - Annual)",
        "L3_KOG_T_A",
        "Transpiration (Koga, Ethiopia - Annual)",
        "L3_LAK_T_A",
        "Transpiration (Lower Akagera, Rwanda - Annual)",
        "L3_LAM_T_A",
        "Transpiration (Lamego, Mozambique - Annual)",
        "L3_MAL_T_A",
        "Transpiration (Malwathu Oya West Sub Catchment, Sri Lanka - Annual)",
        "L3_MUV_T_A",
        "Transpiration (Muvumba catchment, Rwanda - Annual)",
        "L3_ODN_T_A",
        "Transpiration (Office du Niger, Mali - Annual)",
        "L3_SED_T_A",
        "Transpiration (Senegal Delta, Senegal - Annual)",
        "L3_YAN_T_A",
        "Transpiration (Yanze catchment, Rwanda - Annual)",
        "L3_ZAN_T_A",
        "Transpiration (Zankalon, Egypt - Annual)",
        "L3_AWA_E_A",
        "Evaporation (Awash, Ethiopia - Annual)",
        "L3_BKA_E_A",
        "Evaporation (Bekaa, Lebanon - Annual)",
        "L3_BUS_E_A",
        "Evaporation (Busia, Kenya - Annual)",
        "L3_GEZ_E_A",
        "Evaporation (Gezira, Sudan - Annual)",
        "L3_KOG_E_A",
        "Evaporation (Koga, Ethiopia - Annual)",
        "L3_LAK_E_A",
        "Evaporation (Lower Akagera, Rwanda - Annual)",
        "L3_LAM_E_A",
        "Evaporation (Lamego, Mozambique - Annual)",
        "L3_MAL_E_A",
        "Evaporation (Malwathu Oya West Sub Catchment, Sri Lanka - Annual)",
        "L3_MUV_E_A",
        "Evaporation (Muvumba catchment, Rwanda - Annual)",
        "L3_ODN_E_A",
        "Evaporation (Office du Niger, Mali - Annual)",
        "L3_SED_E_A",
        "Evaporation (Senegal Delta, Senegal - Annual)",
        "L3_YAN_E_A",
        "Evaporation (Yanze catchment, Rwanda - Annual)",
        "L3_ZAN_E_A",
        "Evaporation (Zankalon, Egypt - Annual)",
        "L3_AWA_I_A",
        "Interception (Awash, Ethiopia - Annual)",
        "L3_BKA_I_A",
        "Interception (Bekaa, Lebanon - Annual)",
        "L3_BUS_I_A",
        "Interception (Busia, Kenya - Annual)",
        "L3_GEZ_I_A",
        "Interception (Gezira, Sudan - Annual)",
        "L3_KOG_I_A",
        "Interception (Koga, Ethiopia - Annual)",
        "L3_LAK_I_A",
        "Interception (Lower Akagera, Rwanda - Annual)",
        "L3_LAM_I_A",
        "Interception (Lamego, Mozambique - Annual)",
        "L3_MAL_I_A",
        "Interception (Malwathu Oya West Sub Catchment, Sri Lanka - Annual)",
        "L3_MUV_I_A",
        "Interception (Muvumba catchment, Rwanda - Annual)",
        "L3_ODN_I_A",
        "Interception (Office du Niger, Mali - Annual)",
        "L3_SED_I_A",
        "Interception (Senegal Delta, Senegal - Annual)",
        "L3_YAN_I_A",
        "Interception (Yanze catchment, Rwanda - Annual)",
        "L3_ZAN_I_A",
        "Interception (Zankalon, Egypt - Annual)",
        "L3_AWA_T_D",
        "Transpiration (Awash, Ethiopia - Dekadal)",
        "L3_BKA_T_D",
        "Transpiration (Bekaa, Lebanon - Dekadal)",
        "L3_BUS_T_D",
        "Transpiration (Busia, Kenya - Dekadal)",
        "L3_GEZ_T_D",
        "Transpiration (Gezira, Sudan - Dekadal)",
        "L3_KOG_T_D",
        "Transpiration (Koga, Ethiopia - Dekadal)",
        "L3_LAK_T_D",
        "Transpiration (Lower Akagera, Rwanda - Dekadal)",
        "L3_LAM_T_D",
        "Transpiration (Lamego, Mozambique - Dekadal)",
        "L3_MAL_T_D",
        "Transpiration (Malwathu Oya West Sub Catchment, Sri Lanka - Dekadal)",
        "L3_MUV_T_D",
        "Transpiration (Muvumba catchment, Rwanda - Dekadal)",
        "L3_ODN_T_D",
        "Transpiration (Office du Niger, Mali - Dekadal)",
        "L3_SED_T_D",
        "Transpiration (Senegal Delta, Senegal - Dekadal)",
        "L3_YAN_T_D",
        "Transpiration (Yanze catchment, Rwanda - Dekadal)",
        "L3_ZAN_T_D",
        "Transpiration (Zankalon, Egypt - Dekadal)",
        "L3_AWA_E_D",
        "Evaporation (Awash, Ethiopia - Dekadal)",
        "L3_BKA_E_D",
        "Evaporation (Bekaa, Lebanon - Dekadal)",
        "L3_BUS_E_D",
        "Evaporation (Busia, Kenya - Dekadal)",
        "L3_GEZ_E_D",
        "Evaporation (Gezira, Sudan - Dekadal)",
        "L3_KOG_E_D",
        "Evaporation (Koga, Ethiopia - Dekadal)",
        "L3_LAK_E_D",
        "Evaporation (Lower Akagera, Rwanda - Dekadal)",
        "L3_LAM_E_D",
        "Evaporation (Lamego, Mozambique - Dekadal)",
        "L3_MAL_E_D",
        "Evaporation (Malwathu Oya West Sub Catchment, Sri Lanka - Dekadal)",
        "L3_MUV_E_D",
        "Evaporation (Muvumba catchment, Rwanda - Dekadal)",
        "L3_ODN_E_D",
        "Evaporation (Office du Niger, Mali - Dekadal)",
        "L3_SED_E_D",
        "Evaporation (Senegal Delta, Senegal - Dekadal)",
        "L3_YAN_E_D",
        "Evaporation (Yanze catchment, Rwanda - Dekadal)",
        "L3_ZAN_E_D",
        "Evaporation (Zankalon, Egypt - Dekadal)",
        "L3_AWA_I_D",
        "Interception (Awash, Ethiopia - Dekadal)",
        "L3_BKA_I_D",
        "Interception (Bekaa, Lebanon - Dekadal)",
        "L3_BUS_I_D",
        "Interception (Busia, Kenya - Dekadal)",
        "L3_GEZ_I_D",
        "Interception (Gezira, Sudan - Dekadal)",
        "L3_KOG_I_D",
        "Interception (Koga, Ethiopia - Dekadal)",
        "L3_LAK_I_D",
        "Interception (Lower Akagera, Rwanda - Dekadal)",
        "L3_LAM_I_D",
        "Interception (Lamego, Mozambique - Dekadal)",
        "L3_MAL_I_D",
        "Interception (Malwathu Oya West Sub Catchment, Sri Lanka - Dekadal)",
        "L3_MUV_I_D",
        "Interception (Muvumba catchment, Rwanda - Dekadal)",
        "L3_ODN_I_D",
        "Interception (Office du Niger, Mali - Dekadal)",
        "L3_SED_I_D",
        "Interception (Senegal Delta, Senegal - Dekadal)",
        "L3_YAN_I_D",
        "Interception (Yanze catchment, Rwanda - Dekadal)",
        "L3_ZAN_I_D",
        "Interception (Zankalon, Egypt - Dekadal)",
        "L3_AWA_NPP_M",
        "Net Primary Production (Awash, Ethiopia - Monthly)",
        "L3_BKA_NPP_M",
        "Net Primary Production (Bekaa, Lebanon - Monthly)",
        "L3_BUS_NPP_M",
        "Net Primary Production (Busia, Kenya - Monthly)",
        "L3_GEZ_NPP_M",
        "Net Primary Production (Gezira, Sudan - Monthly)",
        "L3_KOG_NPP_M",
        "Net Primary Production (Koga, Ethiopia - Monthly)",
        "L3_LAK_NPP_M",
        "Net Primary Production (Lower Akagera, Rwanda - Monthly)",
        "L3_LAM_NPP_M",
        "Net Primary Production (Lamego, Mozambique - Monthly)",
        "L3_MAL_NPP_M",
        "Net Primary Production (Malwathu Oya West Sub Catchment, Sri Lanka - Monthly)",
        "L3_MUV_NPP_M",
        "Net Primary Production (Muvumba catchment, Rwanda - Monthly)",
        "L3_ODN_NPP_M",
        "Net Primary Production (Office du Niger, Mali - Monthly)",
        "L3_SED_NPP_M",
        "Net Primary Production (Senegal Delta, Senegal - Monthly)",
        "L3_YAN_NPP_M",
        "Net Primary Production (Yanze catchment, Rwanda - Monthly)",
        "L3_ZAN_NPP_M",
        "Net Primary Production (Zankalon, Egypt - Monthly)",
        "L3_AWA_NPP_D",
        "Net Primary Production (Awash, Ethiopia - Dekadal)",
        "L3_BKA_NPP_D",
        "Net Primary Production (Bekaa, Lebanon - Dekadal)",
        "L3_BUS_NPP_D",
        "Net Primary Production (Busia, Kenya - Dekadal)",
        "L3_GEZ_NPP_D",
        "Net Primary Production (Gezira, Sudan - Dekadal)",
        "L3_KOG_NPP_D",
        "Net Primary Production (Koga, Ethiopia - Dekadal)",
        "L3_LAK_NPP_D",
        "Net Primary Production (Lower Akagera, Rwanda - Dekadal)",
        "L3_LAM_NPP_D",
        "Net Primary Production (Lamego, Mozambique - Dekadal)",
        "L3_MAL_NPP_D",
        "Net Primary Production (Malwathu Oya West Sub Catchment, Sri Lanka - Dekadal)",
        "L3_MUV_NPP_D",
        "Net Primary Production (Muvumba catchment, Rwanda - Dekadal)",
        "L3_ODN_NPP_D",
        "Net Primary Production (Office du Niger, Mali - Dekadal)",
        "L3_SED_NPP_D",
        "Net Primary Production (Senegal Delta, Senegal - Dekadal)",
        "L3_YAN_NPP_D",
        "Net Primary Production (Yanze catchment, Rwanda - Dekadal)",
        "L3_ZAN_NPP_D",
        "Net Primary Production (Zankalon, Egypt - Dekadal)",
        "L3_AWA_TBP_S",
        "Total Biomass Production (Awash, Ethiopia - Seasonal)",
        "L3_BKA_TBP_S",
        "Total Biomass Production (Bekaa, Lebanon - Seasonal)",
        "L3_BUS_TBP_S",
        "Total Biomass Production (Busia, Kenya - Seasonal)",
        "L3_GEZ_TBP_S",
        "Total Biomass Production (Gezira, Sudan - Seasonal)",
        "L3_KOG_TBP_S",
        "Total Biomass Production (Koga, Ethiopia - Seasonal)",
        "L3_LAM_TBP_S",
        "Total Biomass Production (Lamego, Mozambique - Seasonal)",
        "L3_MAL_TBP_S",
        "Total Biomass Production (Malwathu Oya West Sub Catchment, Sri Lanka - Seasonal)",
        "L3_ODN_TBP_S",
        "Total Biomass Production (Office du Niger, Mali - Seasonal)",
        "L3_SED_TBP_S",
        "Total Biomass Production (Senegal Delta, Senegal - Seasonal)",
        "L3_ZAN_TBP_S",
        "Total Biomass Production (Zankalon, Egypt - Seasonal)",
        "L3_AWA_LCC_D",
        "Land Cover Classification (Awash, Ethiopia - Dekadal)",
        "L3_BKA_LCC_D",
        "Land Cover Classification (Bekaa, Lebanon - Dekadal)",
        "L3_KOG_LCC_D",
        "Land Cover Classification (Koga, Ethiopia - Dekadal)",
        "L3_ODN_LCC_D",
        "Land Cover Classification (Office du Niger, Mali - Dekadal)",
        "L3_ZAN_LCC_D",
        "Land Cover Classification (Zankalon, Egypt - Dekadal)",
        "L3_AWA_PHE_S",
        "Phenology (Awash, Ethiopia - Seasonal)",
        "L3_BKA_PHE_S",
        "Phenology (Bekaa, Lebanon - Seasonal)",
        "L3_BUS_PHE_S",
        "Phenology (Busia, Kenya - Seasonal)",
        "L3_GEZ_PHE_S",
        "Phenology (Gezira, Sudan - Seasonal)",
        "L3_KOG_PHE_S",
        "Phenology (Koga, Ethiopia - Seasonal)",
        "L3_LAM_PHE_S",
        "Phenology (Lamego, Mozambique - Seasonal)",
        "L3_MAL_PHE_S",
        "Phenology (Malwathu Oya West Sub Catchment, Sri Lanka - Seasonal)",
        "L3_ODN_PHE_S",
        "Phenology (Office du Niger, Mali - Seasonal)",
        "L3_SED_PHE_S",
        "Phenology (Senegal Delta, Senegal - Seasonal)",
        "L3_ZAN_PHE_S",
        "Phenology (Zankalon, Egypt - Seasonal)",
        "L3_AWA_QUAL_LCC_S",
        "Quality of Land Cover Classification (Awash, Ethiopia - Seasonal)",
        "L3_BKA_QUAL_LCC_S",
        "Quality of Land Cover Classification (Bekaa, Lebanon - Seasonal)",
        "L3_KOG_QUAL_LCC_S",
        "Quality of Land Cover Classification (Koga, Ethiopia - Seasonal)",
        "L3_ODN_QUAL_LCC_S",
        "Quality of Land Cover Classification (Office du Niger, Mali - Seasonal)",
        "L3_ZAN_QUAL_LCC_S",
        "Quality of Land Cover Classification (Zankalon, Egypt - Seasonal)",
        "L3_AWA_QUAL_NDVI_D",
        "Quality of Normalized Difference Vegetation Index (Awash, Ethiopia - Dekadal)",
        "L3_BKA_QUAL_NDVI_D",
        "Quality of Normalized Difference Vegetation Index (Bekaa, Lebanon - Dekadal)",
        "L3_BUS_QUAL_NDVI_D",
        "Quality of Normalized Difference Vegetation Index (Busia, Kenya - Dekadal)",
        "L3_GEZ_QUAL_NDVI_D",
        "Quality of Normalized Difference Vegetation Index (Gezira, Sudan - Dekadal)",
        "L3_KOG_QUAL_NDVI_D",
        "Quality of Normalized Difference Vegetation Index (Koga, Ethiopia - Dekadal)",
        "L3_LAK_QUAL_NDVI_D",
        "Quality of Normalized Difference Vegetation Index (Lower Akagera, Rwanda - Dekadal)",
        "L3_LAM_QUAL_NDVI_D",
        "Quality of Normalized Difference Vegetation Index (Lamego, Mozambique - Dekadal)",
        "L3_MAL_QUAL_NDVI_D",
        "Quality of Normalized Difference Vegetation Index (Malwathu Oya West Sub Catchment, Sri Lanka - Dekadal)",
        "L3_MUV_QUAL_NDVI_D",
        "Quality of Normalized Difference Vegetation Index (Muvumba catchment, Rwanda - Dekadal)",
        "L3_ODN_QUAL_NDVI_D",
        "Quality of Normalized Difference Vegetation Index (Office du Niger, Mali - Dekadal)",
        "L3_SED_QUAL_NDVI_D",
        "Quality of Normalized Difference Vegetation Index (Senegal Delta, Senegal - Dekadal)",
        "L3_YAN_QUAL_NDVI_D",
        "Quality of Normalized Difference Vegetation Index (Yanze catchment, Rwanda - Dekadal)",
        "L3_ZAN_QUAL_NDVI_D",
        "Quality of Normalized Difference Vegetation Index (Zankalon, Egypt - Dekadal)",
        "L3_AWA_QUAL_NDVI_LT",
        "Quality of Normalized Difference Vegetation Index (Awash, Ethiopia - Long Term)",
        "L3_BKA_QUAL_NDVI_LT",
        "Quality of Normalized Difference Vegetation Index (Bekaa, Lebanon - Long Term)",
        "L3_BUS_QUAL_NDVI_LT",
        "Quality of Normalized Difference Vegetation Index (Busia, Kenya - Long Term)",
        "L3_GEZ_QUAL_NDVI_LT",
        "Quality of Normalized Difference Vegetation Index (Gezira, Sudan - Long Term)",
        "L3_KOG_QUAL_NDVI_LT",
        "Quality of Normalized Difference Vegetation Index (Koga, Ethiopia - Long Term)",
        "L3_LAM_QUAL_NDVI_LT",
        "Quality of Normalized Difference Vegetation Index (Lamego, Mozambique - Long Term)",
        "L3_ODN_QUAL_NDVI_LT",
        "Quality of Normalized Difference Vegetation Index (Office du Niger, Mali - Long Term)",
        "L3_ZAN_QUAL_NDVI_LT",
        "Quality of Normalized Difference Vegetation Index (Zankalon, Egypt - Long Term)"
    ])]


@dataclass
class Variable(object):
    cube: Cube

    @property
    def level(self) -> int:
        return int(self.cube.code.split('_')[0][-1])

    @property
    def workspace(self) -> WAPORVersion:
        if self.level == 'L3':
            return wapor_v1
        return wapor_v2


@dataclass
class BBox:
    min_x: float
    min_y: float

    max_x: float
    max_y: float

    projection: int = 4326

    def as_shape(self):
        return {
            "crs": "EPSG:%d" % self.projection,
            "type": "Polygon",
            "coordinates": [
                [
                    [
                        self.min_x,
                        self.max_y
                    ],
                    [
                        self.max_x,
                        self.max_y
                    ],
                    [
                        self.max_x,
                        self.min_y
                    ],
                    [
                        self.min_x,
                        self.min_y
                    ],
                    [
                        self.min_x,
                        self.max_y
                    ]
                ]
            ]
        }
